adobecom/unity

unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js, unitylibs/scripts/utils.js
https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=webanalytics&title=Tag+Specs%3A+Unity+widget
=> Adding analytics for components

unitylibs/core/steps/app-connector.js, unitylibs/core/steps/upload-btn.js, unitylibs/core/styles/styles.css, unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js, unitylibs/scripts/utils.js
1. Add reset on intersection change
2. Prevent default to avoid adding hash to link
3. CSS fix for continue button
=> Intersection reset and no # and css fix

unitylibs/core/styles/styles.css, unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js
MWPW-154956, MWPW-155017 | Fixing the reset issue and padding
=> MWPW-154956, MWPW-155017 | Fixing the reset issue and padding

unitylibs/core/styles/styles.css
MWPW-155115 | Adding new Button animation
=> MWPW-155115 | Adding new Button animation

unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js, unitylibs/scripts/utils.js
MWPW-155513 MWPW-155511 | Prevent default to avoid jump and reset
=> MWPW-155513 MWPW-155511 | Prevent default to avoid jump and reset

unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js
* Avoid duplicate entries for change background operation
Resolves: [MWPW-156191](https://jira.corp.adobe.com/browse/MWPW-156191)
**Test URLs:**
- Before: https://stage--unity--adobecom.hlx.page/drafts/ruchika/remove-background?martech=off
- After: https://ios--unity--adobecom.hlx.page/drafts/ruchika/remove-background?martech=off
=> [MWPW-156191] Avoid duplicate entries for change background operation

unitylibs/core/steps/upload-btn.js
* Fix issue of none of unity workflow working on firefox with uploaded image
Resolves: [MWPW-156247](https://jira.corp.adobe.com/browse/MWPW-156247)
**Test URLs:**
- Before: https://stage--unity--adobecom.hlx.page/drafts/ruchika/remove-background?martech=off
- After: https://mwpw-156247--unity--adobecom.hlx.page/drafts/ruchika/remove-background?martech=off
=> [MWPW-156247] fix firefox issue

unitylibs/core/styles/styles.css
* Add new css for legal text in supplemental text area
Resolves: [MWPW-156392](https://jira.corp.adobe.com/browse/MWPW-156392)
**Test URLs:**
- Before: https://stage--unity--adobecom.hlx.page/drafts/ruchika/remove-background?martech=off
- After: https://MWPW-156392--unity--adobecom.hlx.page/drafts/ruchika/remove-background?martech=off
=> [MWPW-156392] -  Add new css for legal text in supplemental text area

unitylibs/core/steps/app-connector.js, unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js
* Add finalAssetId to payload sent to prelude
Resolves: [MWPW 156395](https://jira.corp.adobe.com/browse/MWPW 156395)
**Test URLs:**
- Before: https://stage--unity--adobecom.hlx.page/drafts/ruchika/edit-photos?martech=off
- After: https://MWPW-156395--unity--adobecom.hlx.page/drafts/ruchika/edit-photos?martech=off
=> [MWPW 156395] - Add finalAssetId to payload sent to prelude

unitylibs/core/steps/upload-btn.js
Showing error prompt for prompt unsupport image
=> MWPW-156284 | Showing error prompt for prompt unsupport image

unitylibs/core/styles/styles.css, unitylibs/scripts/utils.js
Capture analytics for error toast close
=> MWPW-156608 | Capture analytics for error toast close

unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js
=> Revert "[MWPW-156720] Send finalAssetId when only remove background operation is performed"

unitylibs/core/styles/styles.css
MWPW-156696 | Fixing the render issue
Before: https://main--unity--adobecom.hlx.page/unity/unitypages/test-and-demo?georouting=off&martech=off
After: https://imagerender--unity--adobecom.hlx.page/unity/unitypages/test-and-demo?georouting=off&martech=off
Test url: https://stage--cc--adobecom.hlx.page/products/photoshop/remove-background?unitylibs=imagerender
=> MWPW-156696 | Fixing the render issue

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/service-handler.js, unitylibs/core/workflow/workflow-acrobat/target-config.json, unitylibs/core/workflow/workflow.js
* Upload a pdf from UI
* Create chunks to upload on temp urls
* Connector api call for acrobat.
=> Acrobat fill and sign upload functionality

unitylibs/blocks/unity/unity.css, unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/service-handler.js, unitylibs/core/workflow/workflow-acrobat/target-config.json, unitylibs/core/workflow/workflow-photoshop/service-handler.js, unitylibs/core/workflow/workflow.js
=> Animation loader for unity

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/target-config.json, unitylibs/core/workflow/workflow.js
- Map upload and drag & drop functionality
- Extract limits outside of actionMap in config
=> MWPW-157166 Mapping upload functionality to verb-widget

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/scripts/utils.js
https://jira.corp.adobe.com/browse/MWPW-157167
https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=LEO&title=ACP+Integration#ACPIntegration-APIs(ForClientsonboardingtoUnitytoavailGueststorageviaACP)
=> MWPW-157167-Update api request body

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/service-handler.js, unitylibs/core/workflow/workflow-acrobat/target-config.json, unitylibs/core/workflow/workflow.js, unitylibs/scripts/errors.js, unitylibs/scripts/utils.js
- Centralized error handling in Unity UI
- Perform one-time storing of error map in window object for fast lookups downstream
- Created fillsign actionType to consolidate config and break code out into a singleFileUpload function (multiFileUpload can be implemented based on future needs)
=> MWPW-156870 Implementing centralized error handling

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/service-handler.js, unitylibs/core/workflow/workflow-acrobat/target-config.json
Adding check for asset metadata to verify and dispatch an error if the number of pages for the uploaded PDF asset exceeds the max limit.
Resolves: [MWPW-159153](https://jira.corp.adobe.com/browse/MWPW-159153)
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?unitylibs=stage
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?unitylibs=MWPW-159153
=> MWPW-159153 Checking asset metadata

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/service-handler.js
Adding error handling for storage exceeded and no storage provisioned errors.
Resolves: [MWPW-159861](https://jira.corp.adobe.com/browse/MWPW-159861)
Test URLs:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?unitylibs=MWPW-159861
=> MWPW-159861 Handle storage errors

unitylibs/core/workflow/workflow-acrobat/target-config.json
fix issue of file greater than 100 MB getting uploaded
Resolves: [MWPW-160227](https://jira.corp.adobe.com/browse/MWPW-160227)
Test URLs:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?unitylibs=MWPW-160227
=> [MWPW-160227] - fix file greater than 100 MB getting uploaded

unitylibs/core/workflow/workflow-acrobat/target-config.json
Update splash screen fragment path
Resolves: [MWPW-160059](https://jira.corp.adobe.com/browse/MWPW-160059)
Test URLs:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?unitylibs=MWPW-160059
=> [MWPW-160059] Update splash screen fragment path

unitylibs/core/workflow/workflow-acrobat/action-binder.js
Ensure metadata page count is checked even after interval timeout if asset metadata exists. Also, reset operations array if `verifyContent` fails so that redirection to product is interrupted.
Resolves: [MWPW-159947](https://jira.corp.adobe.com/browse/MWPW-159947)
Test URLs:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf?unitylibs=MWPW-159947
=> MWPW-159947 Metadata page count fix after timeout

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/service-handler.js
Adding timeout to finalize API request and including status code when dispatching errors associated with timeouts.
Resolves: [MWPW-160229](https://jira.corp.adobe.com/browse/MWPW-160229)
Test URLs:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf?unitylibs=MWPW-160229
=> MWPW-160229 Adding timeout to finalize API request

unitylibs/core/styles/splash-screen.css, unitylibs/core/workflow/workflow-acrobat/action-binder.js
MWPW-159951 | Stop scrolling when splash screen is visible
Resolves: [MWPW-159951](https://jira.corp.adobe.com/browse/MWPW-159951)
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?unitylibs=MWPW-159951
=> MWPW-159951 | Stop scrolling when splash screen is visible

unitylibs/core/workflow/workflow-acrobat/action-binder.js
Dispatching an analytics event for "redirect to product" when the product handoff is initiated.
Resolves: [MWPW-160448](https://jira.corp.adobe.com/browse/MWPW-160448)
Test URLs:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf?unitylibs=MWPW-160448
=> MWPW-160448 Dispatching analytics event for redirect to product

unitylibs/core/workflow/workflow-acrobat/action-binder.js
Do not fill progress bar to 100 till ready to continue in app
Resolves [MWPW-159948](https://jira.corp.adobe.com/browse/MWPW-159948)
Before - https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?unitylibs=stage
After - https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?unitylibs=MWPW-159948
=> MWPW-159948 | Do not fill progress bar to 100 till ready to continue in app

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/scripts/utils.js
fix issue of page with unity not loading on some versions of safari like 15, 16 etc.
Resolves: [MWPW-160156](https://jira.corp.adobe.com/browse/MWPW-160156)
Test URLs:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?unitylibs=MWPW160156
=> MWPW-160156 -Fix page loading issue on safari

unitylibs/core/workflow/workflow-acrobat/action-binder.js
[TEST] Pass assetData with uploading event to be used to do optimistic prerendering of the product page
=> DCXY-26899 pass data with uploading event

unitylibs/core/steps/app-connector.js, unitylibs/core/workflow/workflow-photoshop/action-binder.js, unitylibs/scripts/utils.js
- Pass ietf code for locale mapping at prelude side
Resolves: [MWPW-156125](https://jira.corp.adobe.com/browse/MWPW-156125)
Test URLs:
Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/remove-background1?unitylibs=stage
After: https://main--cc--adobecom.hlx.page/drafts/ruchika/remove-background1?unitylibs=locale
Note: Code update has been done for both V2 and V1
=> MWPW-156125- Pass ietf code for locale mapping at prelude side

unitylibs/scripts/utils.js
Pass correct ietf for US
Resolves: [MWPW-156125](https://jira.corp.adobe.com/browse/MWPW-156125)
Test URLs:
Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/remove-background1?unitylibs=stage
After: https://main--cc--adobecom.hlx.page/drafts/ruchika/remove-background1?unitylibs=ietf
=> MWPW-156125- Pass correct ietf for US

unitylibs/core/workflow/workflow-acrobat/service-handler.js
Implementing a workaround using IMS refresh token to help resolve 401 errors
Resolves: [MWPW-162484](https://jira.corp.adobe.com/browse/MWPW-162484)
Test URLs:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf?unitylibs=MWPW-162484
=> MWPW-162484 Implementing workaround with  IMS refresh token

unitylibs/core/workflow/workflow-acrobat/service-handler.js
Implementing a workaround using IMS refresh token to help resolve 401 errors
Resolves: [MWPW-162484](https://jira.corp.adobe.com/browse/MWPW-162484)
This was verified on stage: https://github.com/adobecom/unity/pull/151
Test URLs:
Before:
https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf?unitylibs=stage 
After:
https://main--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf?unitylibs=MWPW-162484
=> MWPW-162484 Implementing workaround with  IMS refresh token (#151)

unitylibs/core/styles/styles.css, unitylibs/core/workflow/workflow-photoshop/widget.css, unitylibs/core/workflow/workflow-photoshop/widget.js
**Description:**
This PR implements the figma specs for localization for the Unity widget.
**Resolves:** [MWPW-159204](https://jira.corp.adobe.com/browse/MWPW-159204)
**Test URLs:**
Before: https://stage--unity--adobecom.hlx.page/drafts/rbogos/remove-background
After: https://mwpw-159204-loc--unity--adobecom.hlx.page/drafts/rbogos/remove-background
=> [MWPW-159204] FE Loc Implementation

unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js, unitylibs/scripts/utils.js
This code is only addressing V1 code for Ps considering the urgency.
=> Conditional loading of attributes.js

unitylibs/core/steps/upload-btn.js, unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js, unitylibs/core/workflow/workflow.js, unitylibs/scripts/utils.js
- Conditional loading of attributes.js
- On demand loading of errors.js
- Parallel loading of action-binder.js and target-config.json
- Delaying splash screen initialization to post LCP
https://jira.corp.adobe.com/browse/MWPW-162836
=> MWPW-162836-Unity performance Improvement

unitylibs/core/workflow/workflow-acrobat/action-binder.js
- Fix error loading issue
https://jira.corp.adobe.com/browse/MWPW-163051
Test URLs:
Before: https://main--dc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=stage
After: https://main--dc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=error
=> MWPW-163051-Fix error loading issue

unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js
- Fix hue sat slider for RTL
Resolves: [MWPW-162935](https://jira.corp.adobe.com/browse/MWPW-162935)
Test URLs:
Before: https://stage--cc--adobecom.hlx.page/ae_ar/products/photoshop/ai-photo-editor?unitylibs=stage&georouting=off
After: https://stage--cc--adobecom.hlx.page/ae_ar/products/photoshop/ai-photo-editor?unitylibs=MWPW-162935&georouting=off
Note: Please test LTR page also once
=> MWPW-162935-Fix hue sat slider for RTL

unitylibs/core/styles/styles.css
- Fix button text not visible issue on tab
Resolves: [MWPW-162943](https://jira.corp.adobe.com/browse/MWPW-162943)
Test URLs:
Before: https://stage--cc--adobecom.hlx.page/products/photoshop/ai?unitylibs=stage
After: https://stage--cc--adobecom.hlx.page/products/photoshop/ai?unitylibs=MWPW-162943
=> MWPW-162943-Fix button text not visible issue on tab

unitylibs/core/workflow/workflow-acrobat/action-binder.js
Dispatching custom analytics event when cancel button is clicked.
Resolves: [MWPW-162692](https://jira.corp.adobe.com/browse/MWPW-162692)
Test URLs:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf?unitylibs=MWPW-162692
=> MWPW-162692 Dispatching analytics event for cancel button

unitylibs/core/steps/app-connector.js, unitylibs/core/styles/styles.css, unitylibs/core/workflow/workflow-photoshop/action-binder.js, unitylibs/core/workflow/workflow-photoshop/widget.css, unitylibs/core/workflow/workflow-photoshop/widget.js, unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js, unitylibs/scripts/utils.js
Ps Loc Release
- https://github.com/adobecom/unity/pull/145
- https://github.com/adobecom/unity/pull/148
- https://github.com/adobecom/unity/pull/149
- https://github.com/adobecom/unity/pull/155
- https://github.com/adobecom/unity/pull/161
- https://github.com/adobecom/unity/pull/162
=> [Release] Ps Loc Stage to Main

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/service-handler.js
Sign Pdf Analytics Release
- https://github.com/adobecom/unity/pull/168
- https://github.com/adobecom/unity/pull/160
- https://github.com/adobecom/unity/pull/166
- https://github.com/adobecom/unity/pull/153
=> [Release] Sign Pdf Analytics Stage to Main

unitylibs/core/styles/splash-screen.css
Fixing the issue where a ridge border is showing up for video tag.
=> MWPW-160906 | Border showing up on video on intermediate screen

unitylibs/core/styles/splash-screen.css
Show cancel button till screen width 1000px
Resolves: [MWPW-160611](https://jira.corp.adobe.com/browse/MWPW-160611)
**Before:** https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity
**After:** https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?unitylibs=mwpw-160611
=> MWPW-160611 | Cancel button visibility threshold

tools/sidekick/config.json
Update Unity project sidekick to contain the “Localize project (v2)” option
=> MWPW-163895 Adding Localize v2 option in project sidekick

unitylibs/core/steps/upload-btn.js, unitylibs/core/styles/splash-screen.css, unitylibs/core/styles/styles.css
PRs:
- https://github.com/adobecom/unity/pull/169
- https://github.com/adobecom/unity/pull/154
- https://github.com/adobecom/unity/pull/172
- https://github.com/adobecom/unity/pull/171
Test URLs:
Before: https://main--cc--adobecom.hlx.page/fr/products/photoshop/ai?unitylibs=main&georouting=off
After: https://main--cc--adobecom.hlx.page/fr/products/photoshop/ai?unitylibs=main-sync&georouting=off
=> [Release] Remove tooltip from Upload Button | Cancel button visibility threshold | Border Issue

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/target-config.json
Setting up target config for Compress PDF with updated limits
Resolves: [MWPW-163776](https://jira.corp.adobe.com/browse/MWPW-163776)
Test URLs:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf?unitylibs=MWPW-163776
=> MWPW-163776 Setting up target config for Compress PDF

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/target-config.json
Handling single file uploads for Compress PDF. Breaking out logic for retrieving the redirect URL and performing validations.
Resolves: [MWPW-163778](https://jira.corp.adobe.com/browse/MWPW-163778)
Test URLs:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf?unitylibs=MWPW-163778
=> MWPW-163778 Handling single file uploads for Compress PDF

unitylibs/core/workflow/workflow-acrobat/target-config.json, unitylibs/core/workflow/workflow.js
This PR needs to get merged along with https://github.com/adobecom/unity/pull/180 for compress pdf flow to work.
=> Update workflow.js to support compress-pdf feature

unitylibs/core/workflow/workflow-acrobat/action-binder.js
Handling multi file use case for Compress PDF
Resolves: [MWPW-163779](https://jira.corp.adobe.com/browse/MWPW-163779)
Test URLs:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/compress-pdf?unitylibs=multifile
=> MWPW-163779-Support multi file upload for compress pdf

unitylibs/core/workflow/workflow-acrobat/action-binder.js
Show splash screen for multi file use case
Resolves: [MWPW-163779](https://jira.corp.adobe.com/browse/MWPW-163779)
Test URLs:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/compress-pdf?unitylibs=multi-splash
=> MWPW-163779 - Show splash screen for multi file use case

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/target-config.json
- Batch upload file chunks.
- Keep batch size in config
Resolves: [MWPW-164719](https://jira.corp.adobe.com/browse/MWPW-164719)
Test URLs:
Compress Pdf:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/compress-pdf?unitylibs=batch-upload
Fill & Sign:
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=stage
After: https://stage--dc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=batch-upload
=> MWPW-164719-Batch upload file chunks

unitylibs/core/workflow/workflow-acrobat/action-binder.js
- Show progress bar only till 95%
- Show it only for 2.5 seconds. Currently in stage we have set it up to 5 seconds.
Resolves: [MWPW-163779](https://jira.corp.adobe.com/browse/MWPW-163779)
Test URLs:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/compress-pdf?unitylibs=multi-splash
=> MWPW-163779-Update transition screen for multi file

unitylibs/core/steps/app-connector.js, unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js, unitylibs/scripts/utils.js
URL for testing:
- https://stage--cc--adobecom.hlx.page/creativecloud/animation/testdoc/sarangi-unity/edit-photo?unitylibs=default-cache-MWPW-156635
Note: Redirect to prelude will only work on stage and prod environment.
=> Default image caching

unitylibs/core/styles/splash-screen.css
**Description:**
This PR implements the mobile design requirements from this [figma](https://www.figma.com/design/rhI8Uchn4EFBhwdChdawYD/Frictionless---(L1%2FL2)?node-id=6090-16978&m=dev&focus-id=13414-29398).
**Resolves:** [MWPW-162587](https://jira.corp.adobe.com/browse/MWPW-162587)
**Testing instructions:**
Compare against the figma design.
**Test URLs:**
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/compress-pdf?unitylibs=mwpw-162586-compress-pdf
URL for PSI check: https://mwpw-162586-compress-pdf--unity--adobecom.hlx.page/drafts/ruchika/remove-background?martech=off
=> [MWPW-162587] Splash screen mobile design

unitylibs/core/workflow/workflow-genai/widget.css
* Update aside styles for text to image
Resolves: [MWPW-160536](https://jira.corp.adobe.com/browse/MWPW-160536)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.page/drafts/hnv/text2image-test-page?unitylibs=text-to-image&unityversion=v2
- After: https://stage--cc--adobecom.hlx.page/drafts/hnv/text2image-test-page?unitylibs=aside-styles&unityversion=v2
=> MWPW-160536-Update aside styles for text to image

unitylibs/core/workflow/workflow-acrobat/target-config.json
=> Revert "Reduce the chunk batch sise to 6 for compress-pdf"

unitylibs/core/workflow/workflow-acrobat/action-binder.js
* Fix progress bar issue
Resolves: [MWPW-165846](https://jira.corp.adobe.com/browse/MWPW-165846)
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=stage&martech=off
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=progress&martech=off
=> MWPW-165846-Fix progress bar issue

unitylibs/core/workflow/workflow-acrobat/action-binder.js
* Fix loader percentage issue
Resolves: [MWPW-165846](https://jira.corp.adobe.com/browse/MWPW-165846)
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=loader
=> MWPW-165846-Fix loader percentage issue

.github/pull_request_template.md, unitylibs/core/styles/splash-screen.css, unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/target-config.json, unitylibs/core/workflow/workflow.js, unitylibs/scripts/errors.js
* Compress PDF release
List of PRs
- https://github.com/adobecom/unity/pull/179
- https://github.com/adobecom/unity/pull/180
- https://github.com/adobecom/unity/pull/181
- https://github.com/adobecom/unity/pull/182
- https://github.com/adobecom/unity/pull/183
- https://github.com/adobecom/unity/pull/186
- https://github.com/adobecom/unity/pull/187
- https://github.com/adobecom/unity/pull/188
- https://github.com/adobecom/unity/pull/189
- https://github.com/adobecom/unity/pull/190
- https://github.com/adobecom/unity/pull/191
- https://github.com/adobecom/unity/pull/194
- https://github.com/adobecom/unity/pull/198
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=main&mar …
=> [Main]Compress pdf release

unitylibs/core/workflow/workflow-acrobat/action-binder.js
- Updating multiFileUpload function to handle concurrent uploads
- Cleaning up ActionBinder to consolidate duplicate functionality
Resolves: [MWPW-166349](https://jira.corp.adobe.com/browse/MWPW-166349)
**Test URLs:**
- Before: https://multifile-impl--unity--adobecom.hlx.page/?martech=off
- After: https://MWPW-166349-multifile-upload--unity--adobecom.hlx.page/?martech=off
=> MWPW-166349 Updating multiFileUpload function to handle concurrent uploads

unitylibs/scripts/utils.js
* Allowed `AEM` url in unity utils.
Resolves: [mwpw-164764] (https://jira.corp.adobe.com/browse/mwpw-164764)
**Test URLs:**
- Before: https://hlx-5--cc--adobecom.aem.page/products/photoshop/ai?martech=off
- After: https://hlx-5--cc--adobecom.aem.page/products/photoshop/ai?unitylibs=MWPW-164764&martech=off
=> Fix(mwpw-164764):unity update for helix upgrade.

unitylibs/core/workflow/workflow-acrobat/action-binder.js
- Refactoring action binder to re-order functions for better readability/maintainability
- Fixing linter issues
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=stage&martech=off
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=ab-cleanup&martech=off
=> Cleaning up action binder for acrobat workflow

unitylibs/core/steps/app-connector.js, unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js, unitylibs/scripts/utils.js
Implements caching the default experience for Ps widget
Resolves: [MWPW-156635](https://jira.corp.adobe.com/browse/MWPW-156635)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.page/products/photoshop/remove-background?unitylibs=stage
- After: https://main--cc--adobecom.hlx.page/products/photoshop/remove-background?unitylibs=ps-default-cache
=> [Ps] Default image caching

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-photoshop/widget.js, unitylibs/scripts/utils.js
* Add latest commits to stage back after syncing stage branch with main
**Test URLs:**
- Before: https://stage--unity--adobecom.hlx.page/?martech=off
- After: https://stage-temp-commits--unity--adobecom.hlx.page/?martech=off
=> Add latest commits to stage back after syncing stage branch with main

unitylibs/core/workflow/workflow-acrobat/action-binder.js
Generate workflowId
Resolves: [MWPW-166349](https://jira.corp.adobe.com/browse/MWPW-166349)
Test URLs:
Before: http://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=stage
After: http://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=MWPW-166349-worfklowId
=> MWPW-166349 Generate workflowId

unitylibs/core/workflow/workflow-acrobat/action-binder.js
* Adding concurrency limits per device type
* Updating multifile upload function to use dynamic limits to make parallel calls
Resolves: [MWPW-166349](https://jira.corp.adobe.com/browse/MWPW-166349)
**Test URLs:**
- Before: http://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=stage
- After: http://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=MWPW-166349-concurrency
=> MWPW-166349 Adding concurrent limits

unitylibs/core/workflow/workflow-acrobat/action-binder.js
=> MFU Analytics, Connector and splash screen

unitylibs/core/workflow/workflow-acrobat/action-binder.js
- Optimizing multi-file chunking logic
- Implementing dynamic file & chunk batchSize limits
- Implementing active pool of tasks for chunk processing
Resolves: [MWPW-166350](https://jira.corp.adobe.com/browse/MWPW-166350)
Test URLs:
Before: http://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=stage
After: http://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=MWPW-166350
=> MWPW-166350 Optimize multifile chunking logic

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/scripts/utils.js
* Support multi file upload use case
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=mfu&martech=off
Note: PR needs to be merged to test the signed in flow for multi file upload.
=> MWPW-166261-Multi File Upload

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/scripts/utils.js
* MFU-Update connector api request body
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=mfu-assetid&martech=off
=> MWPW-166261-MFU-Update connector api request body

unitylibs/core/workflow/workflow-ai/action-binder.js, unitylibs/core/workflow/workflow-ai/widget.css, unitylibs/core/workflow/workflow-ai/widget.js
Bug fixes.
Added a divider line to the prompt suggestion tip section.
Fixed the issue where pressing the Enter key in the textbox redirected to the Product page.
Resolves: https://jira.corp.adobe.com/browse/MWPW-167163
https://jira.corp.adobe.com/browse/MWPW-167167
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.page/drafts/hnv/text2image-test-page?unitylibs=stage&unityversion=v2&martech=off
- After: https://stage--cc--adobecom.hlx.page/drafts/hnv/text2image-test-page?unitylibs=t2i-new-req&unityversion=v2&martech=off
=> [MWPW-167163][MWPW-167167]:- Express Text to Image Bug fixes

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/scripts/utils.js
This reverts commit 1fb84601d051352a3119c93cea8c8bc4d9e647bb.
=> Revert "MWPW-166261-MFU-Update connector api request body (#217)"

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/scripts/utils.js
This reverts commit 6234fdb15f922853970b13ca71018c3b3e330190.
=> Revert "MWPW-166261-Multi File Upload (#216)"

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-photoshop/widget.js, unitylibs/scripts/utils.js
This reverts commit 5eb2da85b65301a70c1d4266a63236622181bed6.
=> Revert "Add latest commits to stage back after syncing stage branch with main" (#208)

unitylibs/core/workflow/workflow-acrobat/action-binder.js
- Updating MFU validations and error handling
- Clean up logging
Resolves: [MWPW-166350](https://jira.corp.adobe.com/browse/MWPW-166350)
**Test URLs:**
- Before: http://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=stage
- After: http://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=MWPW-166350-validations
=> MWPW-166350 Updating validations and error handling for MFU uploads

unitylibs/core/workflow/workflow-acrobat/action-binder.js
* Splash screen and redirect url fix for mfu
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=mfu&martech=off
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=mfu-error&martech=off
=> MWPW-166261-Splash screen and redirect url fix for mfu

unitylibs/core/workflow/workflow-acrobat/action-binder.js
- Cleaning up SFU and MFU
Resolves: [MWPW-166350](https://jira.corp.adobe.com/browse/MWPW-166350)
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=mfu-cleanup&martech=off
=> MWPW-166350 SFU and MFU cleanup

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/scripts/utils.js
* Support multi file upload use case
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=mfu&martech=off
Note: PR needs to be merged to test the signed in flow for multi file upload.
=> MWPW-166261 Multi File Upload

unitylibs/core/workflow/workflow-acrobat/action-binder.js
=> Revert "MWPW-166261 Multi File Upload"

unitylibs/core/workflow/workflow-acrobat/action-binder.js
* Optimize sfu
* Fix guest user experience for mfu
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=mfu&martech=off
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=mfu-optimize&martech=off
=> MWPW-166261 - Optimize sfu & Fix guest user experience for mfu

unitylibs/core/workflow/workflow-acrobat/action-binder.js
* Fix splash screen issue for multi file guest user
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=mfu&martech=off
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=mfu-splash&martech=off
=> MWPW-166261-Fix splash screen issue for multi file guest user

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/scripts/utils.js
* Support multi file upload use case
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=mfu&martech=off
Note: PR needs to be merged to test the signed in flow for multi file upload.
=> MWPW-166261-Support multi file upload use case

unitylibs/core/workflow/workflow-acrobat/action-binder.js
* Await the validateFiles function
* Add delay function
* 
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=mfu&martech=off
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=mfu-delay&martech=off
=> MWPW-166261-Wait for validateFiles and create function for delay

unitylibs/core/workflow/workflow-acrobat/action-binder.js
- Ensure entire batch of upload tasks is resolved before continuing to `/finalize`
Resolves: [MWPW-166350](https://jira.corp.adobe.com/browse/MWPW-166350)
Test URLs:
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=mfu-batch-exec&martech=off
=> MWPW-166350 Wait for batch to complete before finalize

unitylibs/core/workflow/workflow-acrobat/action-binder.js
Reverts adobecom/unity#235
* Revert PR to support T2I prod release
=> Revert "MWPW-166261-Support multi file upload use case"

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/scripts/utils.js
=> Revert "Add latest commits to stage back after syncing stage branch with main"

unitylibs/core/workflow/workflow.js, unitylibs/scripts/utils.js
- Fixing workflow.js for t2i prod deployment
Test URLs:
- Before: https://main--cc--adobecom.hlx.page/drafts/hnv/text2image-test-page&martech=off
- After: https://stage--cc--adobecom.hlx.page/drafts/hnv/text2image-test-page?unitylibs=workflow-fix&unityversion=v2&martech=off
=> Fixing workflow.js for t2i prod deployment

unitylibs/core/workflow/workflow.js
Updating `getWorkflowInformation` function
Test URLs:
- Before: https://main--cc--adobecom.hlx.page/drafts/hnv/text2image-test-page&martech=off
- After: https://stage--cc--adobecom.hlx.page/drafts/hnv/text2image-test-page?unitylibs=workflow-fix&unityversion=v2&martech=off
=> Updating getWorkflowInformation function

unitylibs/core/workflow/workflow-ai/action-binder.js, unitylibs/core/workflow/workflow-ai/widget.css, unitylibs/core/workflow/workflow-ai/widget.js
- Layout shift bug fix
- iPhone refresh button click issue
- Increased animation duration
- Opacity fix for the Prompt-bar
Resolves: https://jira.corp.adobe.com/browse/MWPW-167590, https://jira.corp.adobe.com/browse/MWPW-167592,https://jira.corp.adobe.com/browse/MWPW-167299
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.page/drafts/hnv/text2image-test-page?stage&unityversion=v2&martech=off
- After: https://stage--cc--adobecom.hlx.page/drafts/hnv/text2image-test-page?unitylibs=t2i-v2-mig1&unityversion=v2&martech=off
=> [MWPW-167590, MWPW-167592, MWPW-167299] Text to image Enhancement and bug fixes

unitylibs/core/workflow/workflow-acrobat/action-binder.js
* Stablize mfu progress bar for signed in user
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=mfu&martech=off
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=mfu-progressbar&martech=off
=> Stablize mfu progress bar for signed in user

unitylibs/core/workflow/workflow-acrobat/upload-handler.js
* Fixing upload handler references to ActionBinder class variables
Resolves: [MWPW-167747](https://jira.corp.adobe.com/browse/MWPW-167747)
Test URLs:
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=stage&martech=off
After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=MWPW-167747-limits-fix&martech=off
=> MWPW-167747 Fixing upload handler for mfu

unitylibs/core/workflow/workflow-acrobat/upload-handler.js
* Fixing references to ActionBinder class variable
Resolves: [MWPW-167747](https://jira.corp.adobe.com/browse/MWPW-167747)
Test URLs:
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=stage&martech=off
After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylbs=MWPW-167747-limits-fix&martech=off
=> MWPW-167747 Fixing references to ActionBinder class variable

unitylibs/core/workflow/workflow-photoshop/action-binder.js
https://github.com/adobecom/unity/pull/264 PS v2 migration hue sat payload fix
Resolves: [MWPW-157950](https://jira.corp.adobe.com/browse/MWPW-157950)
**Test URLs:**
- Before: https://main--unity--adobecom.hlx.live/drafts/mathuria/edit-photos?unityversion=v1&martech=off
- After: https://psv2huesat--unity--adobecom.hlx.live/drafts/mathuria/edit-photos?martech=off
=> MWPW-157950 | PS v2 migration hue sat payload fix

unitylibs/core/workflow/workflow-acrobat/upload-handler.js
* Fixing failedFiles check for upload such that number of files matches the `uploadResult` size
Resolves: [MWPW-168171](https://jira.corp.adobe.com/browse/MWPW-168171)
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=stage&martech=off
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=chunk-fix&martech=off
=> MWPW-168171 Fixing failedFiles check for upload

.github/pull_request_template.md, test/scripts/utils.test.js, tools/sidekick/config.json, unitylibs/blocks/unity/unity.js, unitylibs/scripts/errors.js, unitylibs/scripts/utils.js
**Description**
This PR contains the required changes to migrate Unity to hlx5.
Resolves: [MWPW-164727](https://jira.corp.adobe.com/browse/MWPW-164727)
**Test URLs:**
- Before: https://stage--unity--adobecom.hlx.page
- After: https://mwpw-164727-hlx5-mgrn--unity--adobecom.hlx.page
=> [MWPW-164727] Updates for hlx5 migration

unitylibs/scripts/utils.js
Load hlx milo libs for hlx and aem for aem
**Test URLs:**
- After: https://hlxandaem--unity--adobecom.aem.page/?martech=off
=> Load hlx milo libs for hlx and aem for aem

unitylibs/core/steps/upload-step.js, unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-ai/service-handler.js, unitylibs/core/workflow/workflow-photoshop/action-binder.js, unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js, unitylibs/scripts/utils.js
=> Revert "MWPW-163640: Refactor token retrieval in common utils to use refreshToken"

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js
- Catch the IMS account type error and show a generic error toast
- Enhance logging of all API requests for acrobat workflow
Resolves: [MWPW-168306](https://jira.corp.adobe.com/browse/MWPW-168306)
Resolves: [MWPW-168382](https://jira.corp.adobe.com/browse/MWPW-168382)
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=acrobat-logs
=> [MWPW-168306, MWPW-168382] Enhancing logging of acrobat workflow errors

unitylibs/core/workflow/workflow-acrobat/action-binder.js
- Fix to ensure that error toast does not show on page load for an account type error
Resolves: [MWPW-168306](https://jira.corp.adobe.com/browse/MWPW-168306)
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=MWPW-168306-fix
=> MWPW-168306 Ensure account type error toast is not visible on page load

unitylibs/core/workflow/workflow-photoshop/action-binder.js, unitylibs/core/workflow/workflow-photoshop/widget.js
* Making continue in app button text bold
* Highlight button blue when subnav tray is open
* Fixing Hue Sat reset issue
Resolves: 
[MWPW-169130](https://jira.corp.adobe.com/browse/MWPW-169130)
[MWPW-169133](https://jira.corp.adobe.com/browse/MWPW-169133)
**Test URLs:**
- Before: https://main--unity--adobecom.aem.live/drafts/mathuria/edit-photos/?martech=off
- After: https://MWPW-169130--unity--adobecom.aem.live/drafts/mathuria/edit-photos?martech=off
=> MWPW-169130 & MWPW-169133 | Fixing UI issues for V2

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js
- Updating error logging for acrobat workflow
- Ensure all generic errors have appropriate meessages
- Separate chunk upload failure logs using a separate error code
Resolves: [MWPW-168382](https://jira.corp.adobe.com/browse/MWPW-168382)
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=MWPW-168382-logs
=> MWPW-168382 Updating error logging for acrobat workflow

unitylibs/core/steps/app-connector.js, unitylibs/core/steps/upload-step.js, unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-ai/service-handler.js, unitylibs/core/workflow/workflow-photoshop/action-binder.js, unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js, unitylibs/scripts/utils.js
=> Revert "MWPW-163640: [BugFix] Refactor token retrieval in common utils to use refreshToken"

unitylibs/core/styles/styles.css, unitylibs/core/workflow/workflow-photoshop/widget.css
PS V2 | Fixing max width for changebg options
Resolves:
[MWPW-169130](https://jira.corp.adobe.com/browse/MWPW-169130)
[MWPW-169218](https://jira.corp.adobe.com/browse/MWPW-169218)
**Test URLs:**
=> MWPW-169130 & MWPW-169218 | PS V2 | [Iphone][loc rtl] Fixing max width for changebg options

unitylibs/blocks/healthcheck/healthcheck.js, unitylibs/core/steps/app-connector.js, unitylibs/core/steps/upload-step.js, unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-ai/service-handler.js, unitylibs/core/workflow/workflow-photoshop/action-binder.js, unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js, unitylibs/scripts/utils.js
Reverts adobecom/unity#302
Test Url
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=stage
After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=revert-302-mwpw-163640-release
=> Revert "[MWPW-163640] : Refactor token retrieval in common utils to use refreshToken"

unitylibs/core/workflow/workflow-acrobat/action-binder.js
- Performance Optimization: Checking user state based on response headers instead of waiting for IMS
- Removing unnecessary generic errors
Resolves: [MWPW-168306](https://jira.corp.adobe.com/browse/MWPW-168306)
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=MWPW-168306-header
=> MWPW-168306 Retrieving user state from Server-Timing header

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js, unitylibs/scripts/transition-screen.js
Modularize splash/transition screen code that currently lives in /workflow-acrobat/action-binder.js.
* Added new `transition-screen.js` to /scripts/ folder.
* Updated `/workflow-acrobat/action-binder.js`
* Updated `/workflow-acrobat/upload-handler.js `
* Transition screen should display as it currently does.
Resolves: [MWPW-168739](https://jira.corp.adobe.com/browse/MWPW-168739)
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?martech=off
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=transition-screen-mod&martech=off
=> MWPW-168739 - Modularize transition screen

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js, unitylibs/scripts/utils.js
- Adding verb attribution for Acrobat Workflow APIs for service dashboards
Resolves: [MWPW-169987](https://jira.corp.adobe.com/browse/MWPW-169987)
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=MWPW-169987
=> MWPW-169987 API Enhancements for Verb Attribution in Service Dashboards

test/scripts/utils.test.js
UTs to improve coverage for common headers and token function
=> UTs for common header and token function

test/scripts/utils.test.js, unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js, unitylibs/core/workflow/workflow.js, unitylibs/scripts/utils.js, unitylibs/utils/FileUtils.js
PRs:
- https://github.com/adobecom/unity/pull/319
- https://github.com/adobecom/unity/pull/320
- https://github.com/adobecom/unity/pull/317
- https://github.com/adobecom/unity/pull/316
- https://github.com/adobecom/unity/pull/323
**Test URLs:**
- Before: https://main--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=main&martech=off
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=stage&martech=off
=> [Release] Stage to Main

unitylibs/core/workflow/workflow-acrobat/action-binder.js
Resolves: [MWPW-170102](https://jira.corp.adobe.com/browse/MWPW-170102)
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=arugupta-MWPW-170102
=> Adding unity user status (new vs returning) in redirect url

test/core/workflow/mocks/upload-body.html, test/core/workflow/workflow.upload.test.js, unitylibs/core/styles/splash-screen.css, unitylibs/core/styles/styles.css, unitylibs/core/workflow/workflow-upload/action-binder.js, unitylibs/core/workflow/workflow-upload/target-config.json, unitylibs/core/workflow/workflow.js
* CC configurable widget
Resolves: [MWPW-168591](https://jira.corp.adobe.com/browse/MWPW-168591)
**Test URLs:**
- Before: https://stage--cc--adobecom.aem.page/drafts/ruchika/unity/upload-image?unitylibs=stage&martech=off
- After: https://stage--cc--adobecom.aem.page/drafts/ruchika/unity/upload-image?unitylibs=unity-ps&martech=off
=> MWPW-168591-CC configurable widget

unitylibs/core/workflow/workflow-upload/action-binder.js, unitylibs/core/workflow/workflow-upload/target-config.json
* Add error message for image dimension
* Update transition screen path
Resolves: [MWPW-168591](https://jira.corp.adobe.com/browse/MWPW-168591)
**Test URLs:**
- Before: https://stage--cc--adobecom.aem.page/drafts/ruchika/unity/upload-image?unitylibs=stage&martech=off
- After: https://stage--cc--adobecom.aem.page/drafts/ruchika/unity/upload-image?unitylibs=ps-error&martech=off
=> MWPW-168591- Add error message for image dimension and Update transition screen path

unitylibs/core/workflow/workflow-acrobat/action-binder.js
Resolves: [MWPW-170102](https://jira.corp.adobe.com/browse/MWPW-170102)
Test URLs:
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=stage
After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=arugupta-170102
=> Move the logic to send userType in redirect url to backend 

unitylibs/core/workflow/workflow-acrobat/action-binder.js
- Parse user attempts count from localStorage and pass data to product via redirect URL [Stage Test]
Resolves: [MWPW-170939](https://jira.corp.adobe.com/browse/MWPW-170939)
**Test URLs:**
- After: https://stage--dc--adobecom.aem.page/acrobat/online/compress-pdf?unitylibs=MWPW-170939-stage-test
=> MWPW-170939 Passing user attempts to Connector API

unitylibs/core/workflow/workflow-upload/action-binder.js, unitylibs/scripts/transition-screen.js
* Handle browser back button
* Handle loader going back to 95 from 100%
* Add analytics event for drag and drop image event
Resolves:
[MWPW-171004](https://jira.corp.adobe.com/browse/MWPW-171004)
[MWPW-171030](https://jira.corp.adobe.com/browse/MWPW-171030)
[MWPW-171051](https://jira.corp.adobe.com/browse/MWPW-171051)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.page/creativecloud/animation/testdoc/remove-background?unitylibs=stage&martech=off
- After: https://stage--cc--adobecom.hlx.page/creativecloud/animation/testdoc/remove-background?unitylibs=cc-phase1-updates&martech=off
=> [MWPW-171051]Enhancement and bug fixes for CC Config Phase 1

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/scripts/utils.js
* Wait for event dispatched from DC acom code to redirect to acrobat web
* The event is dispatched either on successfully sending the uploaded event to AA or after a timeout of 3 seconds
Resolves: [MWPW-170867](https://jira.corp.adobe.com/browse/MWPW-170867)
**Test URLs:**
- Before: https://stage--dc--adobecom.aem.page/acrobat/online/compress-pdf?unitylibs=release-041025&martech=off
- After: https://stage--dc--adobecom.aem.page/acrobat/online/compress-pdf?unitylibs=release-wait-redirect&martech=off
Note: For reference here is the DC code to dispatch the event https://github.com/adobecom/dc/pull/1084/files
=> [MWPW-170867]Wait for event dispatched from DC acom code to redirect to acrobat web

unitylibs/core/workflow/workflow-acrobat/action-binder.js
* Fix error for multi file upload
Resolves: [MWPW-170867](https://jira.corp.adobe.com/browse/MWPW-170867)
**Test URLs:**
- Before: https://stage--dc--adobecom.aem.page/acrobat/online/compress-pdf?unitylibs=release-041025&martech=off
- After: https://stage--dc--adobecom.aem.page/acrobat/online/compress-pdf?unitylibs=fix-redirect&martech=off
=> [MWPW-170867] Fix redirect error for multi file upload

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js
Do not log request headers, it can contain access token.
Do not log storage URL, it contains the AWS credentials
Resolves: [MWPW-170874](https://jira.corp.adobe.com/browse/MWPW-170874)
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=rosahu-MWPW-170874-2&martech=off
=> [MWPW-170874] User token and AWS Security credentials are being logged on splunk

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js
PRs:
- https://github.com/adobecom/unity/pull/333
- https://github.com/adobecom/unity/pull/334
- - https://github.com/adobecom/unity/pull/340
- - https://github.com/adobecom/unity/pull/345
**Test URLs:**
- Before: https://main--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=main
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=release-041025
=> [Release] Hotfix to Main

unitylibs/core/workflow/workflow-upload/action-binder.js, unitylibs/scripts/scripts.js
* Enable lana logging in unity codebase
* Added lana.logs to upload workflow (`workflow-upload/action-binder.js`)
* Logging captured in Splunk
Resolves: [MWPW-170503](https://jira.corp.adobe.com/browse/MWPW-170503)
**Test URLs:**
- Before: https://stage--cc--adobecom.aem.page/drafts/ruchika/unity/upload-image?martech=off
- After: https://stage--cc--adobecom.aem.page/drafts/ruchika/unity/upload-image?unitylibs=splunk-reporting&martech=off
**Testing notes:**
Lana logs have been associated with any errors from the upload block. These logs will show up in the console for verification.
Examples:
- Upload unsupported file type
- Upload image larger than 8k by 8k
=> Enable Lana Logging in Unity

unitylibs/core/workflow/workflow-acrobat/action-binder.js
=> Revert "MWPW-170939 Passing user attempts to Connector API"

unitylibs/core/workflow/workflow-acrobat/action-binder.js
=> Revert "[MWPW-170867]-[STAGE] Wait for event dispatched from DC acom code to redirect to acrobat web"

unitylibs/core/styles/styles.css
* Fix alignment of text in error toast
Resolves: [MWPW-171366](https://jira.corp.adobe.com/browse/MWPW-171366)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.page/creativecloud/animation/testdoc/remove-background?unitylibs=stage&martech=off
- After: https://stage--cc--adobecom.hlx.page/creativecloud/animation/testdoc/remove-background?unitylibs=MWPW-171366&martech=off
=> [MWPW-171366]Fix alignment of text in error toast

unitylibs/core/workflow/workflow-acrobat/action-binder.js
**Description:**
This PR is fixing the exception handling in Acrobat workflow
**Resolves:** [MWPW-171287](https://jira.corp.adobe.com/browse/MWPW-171287)
**Test URLs:**
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?martech=off
After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?martech=off&&unitylibs=mwpw-171287
=> [MWPW-171287] Fix exception handling in Acrobat workflow

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/limits.json
Limits.json is restructured to achieve scalability. Created each unique configuration as a separate key reducing tight coupling between the keys and the configuration.
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=arugupta-2a-MWPW169460
=> Restructuring of limit.json for scalability 

unitylibs/core/workflow/workflow-upload/action-binder.js, unitylibs/core/workflow/workflow-upload/target-config.json, unitylibs/scripts/transition-screen.js, unitylibs/scripts/utils.js
* Unity phase 2
Resolves: [MWPW-170503](https://jira.corp.adobe.com/browse/MWPW-170503)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.page/drafts/ruchika/unity/online?unitylibs=unity-ps-phase2
- After: https://stage--cc--adobecom.aem.page/drafts/ruchika/unity/online?unitylibs=ps2
Note: Currently code points to test fragment for transition screen and dev environment for unity service for testing. It will be updated before raising the PR for stage.
=> MWPW-170503-[Feature Branch]Unity Phase 2

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/target-config.json
* Add your
* Specific
* Features or fixes
Resolves: [MWPW-171666](https://jira.corp.adobe.com/browse/MWPW-171666)
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=arugupta-2a-mfu-fallback
=> Batch2A - Fallback logic in case of single valid file in MFU 

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js
* One argument was missing in the analytics call. Fixed it.
* Error code mapping needed fix
Resolves: [MWPW-171661](https://jira.corp.adobe.com/browse/MWPW-171661)
**Test URLs:**
=> [MWPW-171661] Generic error is being logged in splunk for upload errors

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=quickFix
=> Fixing Error logging on each chunk failure

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow.js
* Update verb name for pdf-to-jpg to pdf-to-image
Resolves: [MWPW-172378](https://jira.corp.adobe.com/browse/MWPW-172378)
**Test URLs:**
- Before: https://stage--dc--adobecom.aem.page/acrobat/online/test/pdf-to-jpg?unitylibs=stage
- After: https://stage--dc--adobecom.aem.page/drafts/ruchika/pdf-to-jpg?unitylibs=verb-name-update
=> [MWPW-172378]Update verb name

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js
Resolves: [MWPW-172031](https://jira.corp.adobe.com/browse/MWPW-172031)
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=cancelIssue
=> Workflow progresses to Finalise call even if cancel is clicked before that

unitylibs/core/workflow/workflow-acrobat/upload-handler.js
Resolves: [MWPW-172895](https://jira.corp.adobe.com/browse/MWPW-172895)
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=mfu-fix-signedin
=> Fixing signed in user mfu upload issue

unitylibs/core/workflow/workflow-acrobat/upload-handler.js
Context : https://github.com/adobecom/unity/pull/392
The above PR is merged to release branch for May 8 release. To enable testing for signedIn user, pushing the fix to stage as well.
=> Pushing the mfu signed in user fix to stage for testing

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/limits.json, unitylibs/core/workflow/workflow-acrobat/target-config.json, unitylibs/core/workflow/workflow-acrobat/upload-handler.js, unitylibs/core/workflow/workflow.js, unitylibs/scripts/utils.js
[MWPW-171408](https://jira.corp.adobe.com/browse/MWPW-171408)
[MWPW-171413](https://jira.corp.adobe.com/browse/MWPW-171413)
[MWPW-171414](https://jira.corp.adobe.com/browse/MWPW-171414)
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/word-to-pdf?unitylibs=stage
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/word-to-pdf?unitylibs=arugupta-2b-config
=> 2b config changes

unitylibs/core/workflow/workflow-upload/action-binder.js
* Fix error sub code issue
Resolves: [MWPW-173435](https://jira.corp.adobe.com/browse/MWPW-173435)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.page/drafts/ruchika/unity/online?unitylibs=stage
- After: https://stage--cc--adobecom.hlx.page/drafts/ruchika/unity/online?unitylibs=error-ps2
=> [MWPW-173435] Fix error sub code issue

unitylibs/core/styles/splash-screen.css, unitylibs/scripts/transition-screen.js
* Fix accessibility issues on transition screen
Resolves: [MWPW-172186](https://jira.corp.adobe.com/browse/MWPW-172186)
**Test URLs:**
DC
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=mwpw-172186-phase1
CC
- Before: https://stage--cc--adobecom.hlx.page/products/photoshop/online?unitylibs=stage
- After: https://stage--cc--adobecom.hlx.page/products/photoshop/online?unitylibs=mwpw-172186-phase1
=> [MWPW-172186] Fix accessibility issues on transition screen

unitylibs/core/workflow/workflow-firefly/target-config.json, unitylibs/core/workflow/workflow-firefly/widget.css, unitylibs/core/workflow/workflow-firefly/widget.js, unitylibs/core/workflow/workflow.js
Getting Firefly Text to Image working on the page.
* Update target-config to use `hero-marquee`.
* Update workflow.js 
* Updates to prompt bar styling to reflect new Figma designs.
Work in progress. Needed to get core logic up so other features can be worked on in tandem.
**To do:**
- Fix tablet/mobile styling
- Add menu carrot icon
- Add Checkmark icon to selected item in dropdown
- Hide verb dropdown when clicking outside of it.
**Test URLs:**
- Before: https://main--cc--adobecom.aem.page/drafts/rclayton/firefly/text-to-image?martech=off
- After: https://main--cc--adobecom.aem.page/drafts/rclayton/firefly/text-to-image?unitylibs=prompt-ui-updates&martech=off
=> Update prompt bar ui

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/limits.json, unitylibs/core/workflow/workflow-acrobat/target-config.json, unitylibs/core/workflow/workflow.js
- Config changes for 2c
- Added limits
- handle non pdf in chat pdf
- multi file signed out support for chat pdf
Resolves: [MWPW-171765](https://jira.corp.adobe.com/browse/MWPW-171765)
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/word-to-pdf?unitylibs=stage
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/word-to-pdf?unitylibs=rosahu-batch2c
=> [MWPW-171765] Acrobat: Batch 2c verbs

unitylibs/core/workflow/workflow-firefly/action-binder.js, unitylibs/core/workflow/workflow-firefly/target-config.json, unitylibs/core/workflow/workflow-firefly/widget.js
* Firefly connector api payload
* code cleanup
* code refactoring
**Test URLs:**
- After: https://main--cc--adobecom.aem.page/drafts/ruchika/unity/firefly/unity-firefly?unitylibs=firefly-connector
=> [MWPW-172411] Firefly connector api 

unitylibs/core/workflow/workflow-acrobat/target-config.json, unitylibs/core/workflow/workflow-acrobat/upload-handler.js
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/test/unity/merge-pdf?unitylibs=stage
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/unity/merge-pdf?unitylibs=bugFixes-2b
=> Fix for sfu post validation check break

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/target-config.json, unitylibs/core/workflow/workflow-acrobat/upload-handler.js
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/test/unity/merge-pdf?unitylibs=stage
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/unity/merge-pdf?unitylibs=2b-error-scenarios
=> non pdf handling for 2b 2c

unitylibs/core/workflow/workflow-firefly/widget.css, unitylibs/core/workflow/workflow-firefly/widget.js
**Updates to verb drop down menu:**
* Style fixes for mobile and tablet.
* Added icon for dropdown button
* Added icon for selected verb in verb dropdown menu.
* Added eventListener to close verb dropdown menu if clicked outside of menu.
* Misc style adjustments
**Test URLs:**
- Before: https://main--cc--adobecom.aem.page/drafts/rclayton/firefly/text-to-image?martech=off
- After: https://main--cc--adobecom.aem.page/drafts/rclayton/firefly/text-to-image?unitylibs=ff-verb-updates&martech=off
=> Verb dropdown updates

unitylibs/core/workflow/workflow-firefly/widget.js
* Firefly GenAI prompt bar analytics
* Code cleanup
Resolves: [MWPW-172420](https://jira.corp.adobe.com/browse/MWPW-172420)
**Test URLs:**
- After: https://main--cc--adobecom.aem.page/drafts/ruchika/unity/firefly/unity-firefly?unitylibs=ff-analytics
=> [MWPW-172420]-Firefly GenAI prompt bar analytics

unitylibs/core/workflow/workflow-firefly/action-binder.js
* fix payload
**Test URLs:**
- After: https://main--cc--adobecom.aem.page/drafts/ruchika/unity/firefly/unity-firefly?unitylibs=payload-fix
=> [MWPW-172411] Fix payload

unitylibs/core/workflow/workflow-firefly/action-binder.js, unitylibs/core/workflow/workflow-firefly/widget.js
* Code optimization and refactoring
**Test URLs:**
- After: https://main--cc--adobecom.aem.page/drafts/ruchika/unity/firefly/unity-firefly?unitylibs=code-optimization
=> [MWPW-172411] Code optimization and refactoring

unitylibs/core/workflow/workflow-firefly/action-binder.js, unitylibs/core/workflow/workflow-firefly/widget.css
* Add error toast notification.
* Added lana logging
* CSS clean up.
**Test URLs:**
- Before: https://main--cc--adobecom.aem.page/drafts/rclayton/firefly/text-to-image?unitylibs=firefly-workflow&martech=off
- After: https://main--cc--adobecom.aem.page/drafts/rclayton/firefly/text-to-image?unitylibs=ff-toast-lana&martech=off
=> FF Toast Error and lana logging

unitylibs/core/workflow/workflow-firefly/action-binder.js, unitylibs/core/workflow/workflow-firefly/widget.js
* Make prompt suggestion dropdown optional
* Fix issue of error message showing up when trying to select prompt from prompt suggestion dropdown
Resolves: [MWPW-173792](https://jira.corp.adobe.com/browse/MWPW-173792)
**Test URLs:**
Page with prompt suggestion dropdown
- Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/unity/firefly/unity-firefly?unitylibs=firefly-workflow
- After: https://main--cc--adobecom.hlx.page/drafts/ruchika/unity/firefly/unity-firefly?unitylibs=prompt-fix
Page without prompt suggestion dropdown
- Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/unity/firefly/unity-firefly1?unitylibs=firefly-workflow
- After: https://main--cc--adobecom.hlx.page/drafts/ruchika/unity/firefly/unity-firefly1?unitylibs=prompt-fix
=> [MWPW-173792]Make prompt suggestion dropdown optional

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/scripts/utils.js
* Parse `isGuestToken` property from IMS access token to identify user type
* Switching back to IMS-based check for user type instead of Akamai Server-Timing header impl
Resolves: [MWPW-173354](https://jira.corp.adobe.com/browse/MWPW-173354)
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=MWPW-173354
=> MWPW-173354 Retrieving user type from IMS access token object

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js
Remove generic errors with more specific ones. Catch failures at more granular level to categorise them into pre upload and upload errors. Need slytherin code changes to support these errors
Corresponding Slytherin PR: https://github.com/adobecom/dc/pull/1193 
Resolves: [MWPW-173667](https://jira.corp.adobe.com/browse/MWPW-173667)
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=rosahu-MWPW-173667
=> [MWPW-173667] Upload errors are also exceptions which could be coming before uplaoding

unitylibs/core/workflow/workflow-acrobat/action-binder.js
* Fix cancel cta issue
Resolves: [MWPW-173835](https://jira.corp.adobe.com/browse/MWPW-173835)
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=release-052225
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=MWPW-173835
=> [MWPW-173835] Fix cancel cta issue

unitylibs/core/workflow/workflow-firefly/action-binder.js, unitylibs/core/workflow/workflow-firefly/target-config.json, unitylibs/core/workflow/workflow-upload/action-binder.js, unitylibs/scripts/splunk-analytics.js
Sending event to splunk for firefly.
Few enhancements in PS and FF as well.
Resolves: [MWPW-173423](https://jira.corp.adobe.com/browse/MWPW-173423)
https://jira.corp.adobe.com/browse/MWPW-173423
**Test URLs:**
Page with prompt suggestion dropdown
Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/unity/firefly/unity-firefly?unitylibs=firefly-workflow
After: https://main--cc--adobecom.hlx.page/drafts/ruchika/unity/firefly/unity-firefly?unitylibs=rosahu-ff-dashboard
Page without prompt suggestion dropdown
Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/unity/firefly/unity-firefly1?unitylibs=firefly-workflow
After: https://main--cc--adobecom.hlx.page/drafts/ruchika/unity/firefly/unity-firefly1?unitylibs=rosahu-ff-dashboard
=> [MWPW-173423] Send analytics to Internal Insights Splunk dashboard

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/scripts/utils.js
- Adding enhanced logging for access token errors
- Provides messages if failure to retrieve token, failure to refresh, etc.
Resolves: [MWPW-173354](https://jira.corp.adobe.com/browse/MWPW-173354)
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=MWPW-173354-token-logs
=> MWPW-173354 Adding enhanced logging for access token errors

unitylibs/core/workflow/workflow-firefly/widget.js
* Prompt analytics event name update
Resolves: [MWPW-172420](https://jira.corp.adobe.com/browse/MWPW-172420)
**Test URLs:**
- After: https://main--cc--adobecom.aem.page/drafts/ruchika/unity/firefly/unity-firefly?unitylibs=analytics-update
=> [MWPW-172420] Prompt analytics event name update

test/core/workflow/mocks/ff-body.html, test/core/workflow/workflow.firefly.test.js
* Unit tests
Resolves: [MWPW-173783](https://jira.corp.adobe.com/browse/MWPW-173783)
**Test URLs:**
- After: https://main--cc--adobecom.aem.page/drafts/ruchika/unity/firefly/unity-firefly?unitylibs=unit-test
=> [MWPW-173783]Unit test

unitylibs/core/workflow/workflow-firefly/widget.js
Updating the aria-label on verb dropdown list for better screen reader experience.
**Test URLs:**
- Before: https://main--cc--adobecom.aem.page/drafts/rclayton/firefly/text-to-image-alt?unitylibs=firefly-workflow&martech=off
- After: https://main--cc--adobecom.aem.page/drafts/rclayton/firefly/text-to-image-alt?unitylibs=ff-aria-label-updates&martech=off
=> FF aria label updates

unitylibs/core/workflow/workflow-firefly/widget.js
* Filter prompt based on environment
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/unity/firefly/unity-firefly?unitylibs=firefly-workflow
- After: https://main--cc--adobecom.hlx.page/drafts/ruchika/unity/firefly/unity-firefly?unitylibs=env-aware
=> [MWPW-172411]Filter prompt based on environment

nala/utils/pr.run.sh
* Update the playwright config file extension (`.cjs`) in `run.sh`
Resolves: [MWPW-173504](https://jira.corp.adobe.com/browse/MWPW-173504)
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=ui-automation
=> [Nala][UNITY] Update the playwright config file extension.

unitylibs/core/workflow/workflow-firefly/widget.css
* Fix alignment of tip section when text goes to next line
Resolves: [MWPW-174142](https://jira.corp.adobe.com/browse/MWPW-174142)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/creativecloud/animation/testdoc/unity/unity-firefly?unitylibs=ff-uifixes
- After: https://stage--cc--adobecom.hlx.live/creativecloud/animation/testdoc/unity/unity-firefly?unitylibs=landscape-mode
=> [MWPW-174142] Fix alignment of tip section when text goes to next line

unitylibs/core/workflow/workflow-firefly/widget.css
* Aligning verb dropdown menu with prompt bar containers starting edge, all breakpoints.
* Fix alignment of tip section when text goes to next line
Resolves: [MWPW-174141](https://jira.corp.adobe.com/browse/MWPW-174141)
[MWPW-174142](https://jira.corp.adobe.com/browse/MWPW-174142)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.live/creativecloud/animation/testdoc/unity/unity-firefly?unitylibs=stage
- After: https://stage--cc--adobecom.hlx.live/creativecloud/animation/testdoc/unity/unity-firefly?unitylibs=ff-uifixes
**Note:** PR for both these issues have been reviewed and verified in feature branch. Please see below pull requests
https://github.com/adobecom/unity/pull/456
https://github.com/adobecom/unity/pull/459
=> Firefly UI fixes

nala/features/pdf-editor/pdf-editor.page.cjs, nala/features/pdf-editor/pdf-editor.spec.cjs, nala/features/pdf-editor/pdf-editor.test.cjs
* Automation Test Script for Acrobat PDF-Editor
* Specific
* Features or fixes
Resolves: [MWPW-174158](https://jira.corp.adobe.com/browse/MWPW-174158)
**Test URLs:**
- After: https://pdf-editor--unity--adobecom.aem.page/?martech=off
Branch Test Pages
- https://stage--dc--adobecom.aem.page/?unitylibs=pdf-editor
=> [MWPW-174158] [NALA][UNITY] Add UI Automation Test Script for Acrobat PDF-Editor

unitylibs/core/workflow/workflow-firefly/widget.js
* Aria label for generate button should be updated when verb is changed in dropdown
* Aria label for values in verb dropdown should be localized
Resolves: [MWPW-174303](https://jira.corp.adobe.com/browse/MWPW-174303)
**Test URLs:**
- Before:  https://main--cc--adobecom.hlx.page/drafts/rclayton/firefly/text-to-image?unitylibs=firefly-accessibility&martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/rclayton/firefly/text-to-image?unitylibs=aria-label-fix&martech=off
=> Fix aria label issue for firelfy workflow

unitylibs/core/workflow/workflow-firefly/action-binder.js, unitylibs/core/workflow/workflow-firefly/widget.css, unitylibs/core/workflow/workflow-firefly/widget.js
Resolving all accessibility tickets for Firefly widget
Resolves:
https://jira.corp.adobe.com/browse/MWPW-174303
https://jira.corp.adobe.com/browse/MWPW-174302
https://jira.corp.adobe.com/browse/MWPW-174301
https://jira.corp.adobe.com/browse/MWPW-174300
https://jira.corp.adobe.com/browse/MWPW-174318
**Test URLs:**
Page with prompt suggestion dropdown
- Before:  https://main--cc--adobecom.hlx.page/drafts/rclayton/firefly/text-to-image?unitylibs=stage&martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/rclayton/firefly/text-to-image?unitylibs=firefly-accessibility&martech=off
Page without prompt suggestion dropdown
- Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/unity/firefly/unity-firefly1?unitylibs=stage
- After: …
=> Firefly accessibility updates

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js
While syncing stage with main, stage version of uploadMultiFIle function was retained due to complex conflicts in that. This PR syncs uploadMultiFIle with main version addressing all conflicts.
**Test URLs:**
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/merge-pdf?unitylibs=stage
After: https://stage--dc--adobecom.hlx.page/acrobat/online/merge-pdf?unitylibs=stg-to-main-sync
=> Syncing uploadMultiFIle function with the version on main

unitylibs/core/workflow/workflow-acrobat/action-binder.js
Added timeout of 60 seconds in fetch API call
Resolves: [MWPW-171797](https://jira.corp.adobe.com/browse/MWPW-171797)
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=MWPW-171797
=> [MWPW-171797] Introduce timeout to all fetch calls being made

unitylibs/core/workflow/workflow-acrobat/action-binder.js
For more than 1 input validation failures, show the first error instead of the generic error on toast. Also simplified the error desc code.
Resolves: [MWPW-174632](https://jira.corp.adobe.com/browse/MWPW-174632)
**Test URLs:**
- After: https://stage--dc--adobecom.aem.page/acrobat/online/compress-pdf?unitylibs=MWPW-174632
=> [MWPW-174632] Getting 'unable to process the request' error toast for 'Empty File + Max File Size' upload for 2b/2c

unitylibs/scripts/utils.js
Resolves: [MWPW-174041](https://jira.corp.adobe.com/browse/MWPW-174041)
**Test URLs:**
- After: https://stage--dc--adobecom.aem.page/acrobat/online/compress-pdf?unitylibs=imsEnhancements
=> Sending error object in addition to error message in case of IMS token failures

unitylibs/core/workflow/workflow-firefly/action-binder.js
Remove error toast for empty prompt submission.
Resolves: [MWPW-175347](https://jira.corp.adobe.com/browse/MWPW-175347), [MWPW-175268](https://jira.corp.adobe.com/browse/MWPW-175268)
**Test URLs:**
- Before: https://main--cc--adobecom.aem.live/drafts/rclayton/firefly/golive/ai-video-generator?martech=off
- After: https://main--cc--adobecom.aem.live/drafts/rclayton/firefly/golive/ai-video-generator?unitylibs=ff-empty-generate&martech=off
=> Allow empty query

unitylibs/core/styles/splash-screen.css, unitylibs/scripts/transition-screen.js
* Replacing "One moment as we take you to acrobat.adobe.com" h2 tag with p. Updated css so that the tag change does not affect the text css.
Resolves: [MWPW-173462](https://jira.corp.adobe.com/browse/MWPW-173462)
Testing Notes:
The transition screen UI, specially the font size, style, weight and line height of the texts should remain same with and without this PR.
We also need to verify the above for backward compatibility. This can be done for validating the US pages and ROW pages. Authoring changes for US pages are supposed to be completed within a day or 2, the ROW cahnges can take some time. 
Validation needs to be done for Acrobat as well as Photoshop.
**Test URLs:**
- After: …
=> [MWPW-173462] Loading screen: Text should not be marked as a heading

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/scripts/utils.js
Have improved the logging to have more clarity into the actual error returned by imslib apis. 
This is phase 1, raising the pr to merge on stage to validate the data on field.
**Test URLs:**
- After: https://stage--dc--adobecom.aem.page/acrobat/online/compress-pdf?unitylibs=arugupta-imsEnhancements
=> IMS error logging improvement - Phase 1

test/core/workflow/workflow-acrobat/action-binder.test.js, test/core/workflow/workflow-acrobat/upload-handler.test.js
* Resolving unit tests that were failing within the Acrobat workflow
Resolves: [MWPW-176257](https://jira.corp.adobe.com/browse/MWPW-176257)
URL for testing:
- https://stage--dc--adobecom.aem.page/acrobat/online/compress-pdf?unitylibs=MWPW-176257
=> MWPW-176257 Resolve Acrobat Unit Test Errors

unitylibs/core/workflow/workflow-acrobat/action-binder.js
* This is a POC code done to test the integration of target in unity. Need to merge to stage since the target integration can only work on stage or prod.
Resolves: [MWPW-174296](https://jira.corp.adobe.com/browse/MWPW-174296)
**Test URLs:**
=> [To be Reverted] [POC] [MWPW-174296] fetch activity for mbox id ACOM_UNITY_ACROBAT_EDITPDF_POC from target

unitylibs/core/workflow/workflow-acrobat/action-binder.js
This reverts commit 59516c51a8dbb338ef51b29d95492e4f5e63b734.
* Add your
* Specific
* Features or fixes
**Test URLs:**
=> Revert "[To be Reverted] [POC] [MWPW-174296] fetch activity for mbox id ACOM_UNITY_ACROBAT_EDITPDF_POC from target (#503)"

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/target-config.json
fetch target campaign for mboxid 'ACOM_UNITY_ACROBAT_EDITPDF_POC' for number-pages verb
Resolves: [MWPW-174296](https://jira.corp.adobe.com/browse/MWPW-174296)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/products/photoshop/online?unitylibs=main
- After: https://main--cc--adobecom.hlx.live/products/photoshop/online?unitylibs=MWPW-17429
=> [MWPW-174296] [Unity A/B Testing Framework] Integrate Target - phase 1

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/target-config.json
Revert the temp PRs meant for target integration POC.
Resolves: [MWPW-174296](https://jira.corp.adobe.com/browse/MWPW-174296)
**Test URLs:**
- Before: https://stage--dc--adobecom.aem.page/acrobat/online/compress-pdf
- After: https://stage--dc--adobecom.aem.page/acrobat/online/compress-pdf?unitylibs=revert-target
=> Revert target integration PRs

test/core/workflow/workflow.firefly.test.js
* Adding new unit tests to up coverage.
* This will be a phased effort.
Resolves: [MWPW-175544](https://jira.corp.adobe.com/browse/MWPW-175544)
**Test URLs:**
- Before: https://main--unity--adobecom.aem.page/docs/firefly/firefly-prompt1?martech=off
- After: https://ff-unit-test-updates--unity--adobecom.aem.page/docs/firefly/firefly-prompt1?martech=off
1. Error Handling Tests
2. Input validation with length limits
3. Network error handling in generateContent
4. Graceful error handling in execActions
5. Dropdown Interaction Tests
6. Show/hide dropdown functionality
7. Outside click handling
8. Dropdown reset behavior
9. UnityWidget Additional Tests
10. Verb dropdown creation
11. Limited display prompts
12. Prompt map creation
13. Invalid prompt filtering
14. Accessibility Tests
15. …
=> FF unit test coverage updates

nala/features/add-pdf/add-pdf-number.test.cjs, nala/features/compress-pdf/compress-pdf.test.cjs, nala/features/crop-pdf/crop-pdf.test.cjs, nala/features/delete-pdf/delete-pdf.test.cjs, nala/features/excel-pdf/excel-to-pdf.test.cjs, nala/features/extract-pages/extract-pdf.test.cjs, nala/features/jpg-pdf/jpg-to-pdf.test.cjs, nala/features/pdf-editor/pdf-editor.test.cjs, nala/features/pdf-excel/pdf-to-excel.test.cjs, nala/features/pdf-jpg/pdf-to-jpg.test.cjs, nala/features/pdf-ppt/pdf-to-ppt.test.cjs, nala/features/pdf-word/pdf-word.test.cjs, nala/features/png-pdf/png-to-pdf.test.cjs, nala/features/ppt-pdf/ppt-to-pdf.test.cjs, nala/features/rearrange-pdf/rearrange.test.cjs, nala/features/request-signature/request-signature.test.cjs, nala/features/split-pdf/split-pdf.test.cjs, nala/features/word-pdf/word-to-pdf.test.cjs, playwright.config.cjs
The Nala tests were taking approximately **15 minutes** to complete.  Reduce test execution time by **90%** (from 15 minutes to 2 minutes)
- **Problem**: Tests were running with only 1 worker (`workers: 1`)
- **Impact**: All tests ran sequentially instead of in parallel
- **Solution**: Increased workers to 4 (CI) and 6 (local)
- **Problem**: Each test had two `waitForTimeout(10000)` calls (20 seconds total)
- **Impact**: Tests waited unnecessarily even when elements were ready
- **Solution**: Replaced with proper waiting mechanisms
- **Problem**: Test timeout was 30s, action timeout was 60s
- **Impact**: Tests could hang for extended periods
- **Solution**: Reduced to 20s and 30s respectively
- **Problem**: Tests were waiting for file inputs to be `visible` but they're intentionally …
=> [MWPW-177571] improved parallelism for running lana test cases for optimising execution time

nala/features/add-pdf/add-pdf-number.test.cjs, nala/features/compress-pdf/compress-pdf.test.cjs, nala/features/crop-pdf/crop-pdf.test.cjs, nala/features/delete-pdf/delete-pdf.test.cjs, nala/features/excel-pdf/excel-to-pdf.test.cjs, nala/features/extract-pages/extract-pdf.test.cjs, nala/features/jpg-pdf/jpg-to-pdf.test.cjs, nala/features/pdf-editor/pdf-editor.test.cjs, nala/features/pdf-excel/pdf-to-excel.test.cjs, nala/features/pdf-jpg/pdf-to-jpg.test.cjs, nala/features/pdf-ppt/pdf-to-ppt.test.cjs, nala/features/pdf-word/pdf-word.test.cjs, nala/features/png-pdf/png-to-pdf.test.cjs, nala/features/ppt-pdf/ppt-to-pdf.test.cjs, nala/features/rearrange-pdf/rearrange.test.cjs, nala/features/request-signature/request-signature.test.cjs, nala/features/split-pdf/split-pdf.test.cjs, nala/features/word-pdf/word-to-pdf.test.cjs, test/core/workflow/workflow-acrobat/action-binder.test.js, unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-upload/action-binder.js
Resolves: [MWPW-177528](https://jira.corp.adobe.com/browse/MWPW-177528)
This was caused by https://github.com/adobecom/unity/pull/525 
Now loading the transition screen asynchronously on page load. In rare cases if the user initiates the file upload workflow before the loading is completed, we will load the transition screen synchronously on file upload
**Testing notes:**
- This impacts Acrobat and Photoshop workflows
- Please validate no issue is encountered on file upload across devices and varied network bandwidth. Need to trigger the workflows multiple times to ensure there are no intermittent issues
cc: @sigadamvenkata
**Test URLs:**
Before: https://stage--dc--adobecom.aem.live/acrobat/online/merge-pdf?unitylibs=stage
After: …
=> [MWPW-177528] Delay in file upload across Acrobat and Ps in stage

unitylibs/core/workflow/workflow-photoshop/widget.css, unitylibs/core/workflow/workflow-photoshop/widget.js
* Fix hue/sat slider for RTL
Resolves: [MWPW-174787](https://jira.corp.adobe.com/browse/MWPW-174787)
**Test URLs:**
- Before: https://main--cc--adobecom.aem.page/il_he/products/photoshop/ai-photo-editor?unitylibs=stage
- After: https://main--cc--adobecom.aem.page/il_he/products/photoshop/ai-photo-editor?unitylibs=rtl
=> [MWPW-174787] Fix slider for RTL

nala/features/add-pdf/add-pdf-number.test.cjs, nala/features/compress-pdf/compress-pdf.test.cjs, nala/features/crop-pdf/crop-pdf.test.cjs, nala/features/delete-pdf/delete-pdf.test.cjs, nala/features/excel-pdf/excel-to-pdf.test.cjs, nala/features/extract-pages/extract-pdf.test.cjs, nala/features/jpg-pdf/jpg-to-pdf.test.cjs, nala/features/pdf-editor/pdf-editor.test.cjs, nala/features/pdf-excel/pdf-to-excel.test.cjs, nala/features/pdf-jpg/pdf-to-jpg.test.cjs, nala/features/pdf-ppt/pdf-to-ppt.test.cjs, nala/features/pdf-word/pdf-word.test.cjs, nala/features/png-pdf/png-to-pdf.test.cjs, nala/features/ppt-pdf/ppt-to-pdf.test.cjs, nala/features/rearrange-pdf/rearrange.test.cjs, nala/features/request-signature/request-signature.test.cjs, nala/features/split-pdf/split-pdf.test.cjs, nala/features/word-pdf/word-to-pdf.test.cjs, playwright.config.cjs
Reverted Nala changes in PRs: https://github.com/adobecom/unity/pull/528/file and https://github.com/adobecom/unity/pull/529
Resolves: [MWPW-178554](https://jira.corp.adobe.com/browse/MWPW-178554)
**Test URLs:**
- Before: https://stage--dc--adobecom.aem.page/acrobat/online/compress-pdf
- After: https://stage--dc--adobecom.aem.page/acrobat/online/compress-pdf?unitylibs=rosahu-nala-fix
=> Fix Nala tests "skipping" URL validation

.github/workflows/run-nala-default.yml, nala/utils/pr.run.sh
* Added a `matrix.browser` strategy in the workflow to fan out jobs for chromium, firefox
* Updated `pr.run.sh` to accept a browser argument and run Playwright tests only for the specified project.
Resolves: [MWPW-180856](https://jira.corp.adobe.com/browse/MWPW-180856)
**Test URLs:**
- After: https://nala-fix--unity--adobecom.aem.page/?martech=off
=> [MWPW-180856][NALA] Optimize Nala GitHub Action execution speed by parallelizing browser test runs
