unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.css
Mwpw 155517 | Safari fix to prevent BG tray expanding till the borders
=> Mwpw 155517 | Safari fix to prevent BG tray expanding till the borders

unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js
* Send finalAssetId when only remove background operation is performed
Resolves: [MWPW-156720](https://jira.corp.adobe.com/browse/MWPW-156720)
**Test URLs:**
- Before: https://stage--unity--adobecom.hlx.page/drafts/ruchika/remove-background?martech=off
- After: https://finalassetid--unity--adobecom.hlx.page/drafts/ruchika/remove-background?martech=off
=> [MWPW-156720] Send finalAssetId when only remove background operation is performed

unitylibs/core/styles/splash-screen.css, unitylibs/core/workflow/workflow-acrobat/action-binder.js
Splash screen is not over the jarvis chat if same is enabled on the page. Increasing the z-index to be over jarvis.
Resolves: [MWPW-159953](https://jira.corp.adobe.com/browse/MWPW-159953)
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf?martech=off
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf?martech=off&unitylibs=MWPW-159953
=> MWPW-159953 | Bring splash screen above jarvis chat

unitylibs/core/workflow/workflow-acrobat/action-binder.js
Increasing timeout for finalize API to 80 seconds to provide enough buffer for backend request.
Resolves: [MWPW-160894](https://jira.corp.adobe.com/browse/MWPW-160894)
Test URLs:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf?unitylibs=MWPW-160894
=> MWPW-160894 Increasing finalize timeout to 80 seconds

unitylibs/core/workflow/workflow-photoshop/widget.js
- Remove thumbnail from authoring for change background in unity block for V2
- This update is done to fix an issue with html localization flow https://github.com/adobe/helix-html2md/issues/555
Resolves: [MWPW-159445](https://jira.corp.adobe.com/browse/MWPW-159445)
Test URLs:
Before:
https://stage--unity--adobecom.hlx.page/drafts/ruchika/remove-background
After:
https://thumbnail-v2--unity--adobecom.hlx.page/drafts/ruchika/remove-background
=> MWPW-159445-Remove thumbnail from authoring for change background in unity block for V2

unitylibs/scripts/utils.js
- Pass locale code for locale mapping at prelude side
Resolves: [MWPW-162832](https://jira.corp.adobe.com/browse/MWPW-162832)
Test URLs:
Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/remove-background1?unitylibs=stage
After: https://main--cc--adobecom.hlx.page/drafts/ruchika/remove-background1?unitylibs=locale-code
=> MWPW-162832- Pass locale code to prelude

unitylibs/core/workflow/workflow-acrobat/action-binder.js
- Add cookie check for upload events before redirect
Resolves: [MWPW-162758](https://jira.corp.adobe.com/browse/MWPW-162758)
Test URLs:
Before: https://stage--cc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=stage
After: https://stage--cc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=analytics-cookie
Note: As the cookie is set only for adobe.com domain test by accessing above url on stage.adobe.com and overriding the action-binder.js with the code form this feature branch
=> MWPW-162758-Add cookie check for upload events

unitylibs/core/workflow/workflow-acrobat/action-binder.js
- Check only UTS_Uploaded cookie
Resolves: [MWPW-162758](https://jira.corp.adobe.com/browse/MWPW-162758)
Test URLs:
Before: https://stage--cc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=stage
After: https://stage--cc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=cookie
Note: As the cookie is set only for adobe.com domain test by accessing above url on stage.adobe.com and overriding the action-binder.js with the code form this feature branch
=> MWPW-162758-Check only UTS_Uploaded cookie

unitylibs/core/steps/upload-btn.js, unitylibs/core/styles/styles.css
- Remove default tooltip from Upload button that comes with file upload input element
Resolves: [MWPW-163260](https://jira.corp.adobe.com/browse/MWPW-163260)
Test URLs:
Before: https://stage--cc--adobecom.hlx.page/fr/products/photoshop/ai?unitylibs=stage&georouting=off
After: https://stage--cc--adobecom.hlx.page/fr/products/photoshop/ai?unitylibs=upload-tooltip&georouting=off
=> MWPW-163260-Remove tooltip from Upload button

unitylibs/core/styles/splash-screen.css
Fixing the issue where a ridge border is showing up for video tag.
Resolves : https://jira.corp.adobe.com/browse/MWPW-160906
=> MWPW-160906 | Border showing up on video on intermediate screen

unitylibs/scripts/errors.js
Fixing localized path for errors json for retrieving data from localized error sheet
NOTE: This change is backwards-compatible and would not impact functionality on the existing US production page.
Resolves: [MWPW-164125](https://jira.corp.adobe.com/browse/MWPW-164125)
Test URLs:
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=stage
After: https://stage--dc--adobecom.hlx.live/acrobat/online/sign-pdf?unitylibs=MWPW-164125
=> MWPW-164125 Fixing localized path for errors json

unitylibs/core/workflow/workflow-acrobat/action-binder.js
Ensuring feedback value is included into connector payload for signed-in single file nonPdf upload
Resolves: [MWPW-163778](https://jira.corp.adobe.com/browse/MWPW-163778)
Test URLs:
After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf?unitylibs=MWPW-163778
=> MWPW-163778 Including feedback value for signed-in single file nonPdf upload

unitylibs/core/styles/splash-screen.css, unitylibs/core/workflow/workflow-acrobat/target-config.json
- This update is only for desktop to support already live Fill and Sign use case as F&S only has unity experience for Desktop only.
- Mobile design for splash screen will be handled as part of this ticket for Compress https://jira.corp.adobe.com/browse/MWPW-162586
Resolves: [MWPW-164631](https://jira.corp.adobe.com/browse/MWPW-164631)
Test URLs:
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=stage
After: https://stage--dc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=splash-desktop
Above url will not show the exact change as authoring updates have not been done. Changes can be tested here Test URLs:
https://stage--dc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=splash where an updated test fragment has been mapped.
**Note**: This PR needs to …
=> [Stage]MWPW-164631-Update splash screen as per the new design

unitylibs/core/styles/splash-screen.css
- This update is only for desktop to support already live Fill and Sign use case as F&S has unity experience for Desktop only.
- Mobile design for splash screen will be handled as part of this ticket for Compress https://jira.corp.adobe.com/browse/MWPW-162586
Resolves: [MWPW-164631](https://jira.corp.adobe.com/browse/MWPW-164631)
Test URLs:
Before: https://main--dc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=main
After: https://main--dc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=splash-main
Above url will not show the exact change as authoring updates have not been done. Changes can be tested here Test URLs:
https://main--dc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=splash where an updated test fragment has been mapped.
**Note**: This PR needs to get merged …
=> [Main]MWPW-164631-Update splash screen as per the new design

unitylibs/scripts/errors.js
Enable fetching of verb error JSON file to be environment-aware
Resolves: [MWPW-164846](https://jira.corp.adobe.com/browse/MWPW-164846)
Test URLs:
After: https://stage--dc--adobecom.hlx.live/acrobat/online/test/compress-pdf?unitylibs=MWPW-164846
=> MWPW-164846 Enable fetching of error JSON file to be environment-aware

unitylibs/core/workflow/workflow-acrobat/target-config.json
Updating allowed file types to include additional non-PDF formats
Resolves: [MWPW-163777](https://jira.corp.adobe.com/browse/MWPW-163777)
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/test/compress-pdf?unitylibs=stage&martech=off
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/compress-pdf?unitylibs=MWPW-163777&martech=off
=> MWPW-163777 Updating allowed file types list for CPDF

unitylibs/core/workflow/workflow.js
* Temporary load express page in CC with Unity V2
Resolves: [MWPW-167318](https://jira.corp.adobe.com/browse/MWPW-167318)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/hnv/text2image-test-page?unitylibs=stage&martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/hnv/text2image-test-page?unitylibs=v2-express&martech=off
=> MWPW-167318-Temporary load express page in CC with Unity V2

unitylibs/core/features/progress-circle/progress-circle.js
Fix update progress-circle not loading
Resolves: [MWPW-168084](https://jira.corp.adobe.com/browse/MWPW-168084)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.page/products/photoshop/remove-background?martech=off
- After: https://v2fix--unity--adobecom.hlx.page/drafts/mathuria/remove-background?unityversion=v1&martech=off
=> MWPW-168084 | Fix update progress-circle not loading

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/target-config.json, unitylibs/core/workflow/workflow-acrobat/upload-handler.js, unitylibs/core/workflow/workflow-photoshop/action-binder.js, unitylibs/core/workflow/workflow.js
Adding support for acrobat 1a verbs:
-   add-comment
-   number-pages
-   split-pdf
-   crop-pages
Supports
- Single file upload
- Only PDF for add-comment, number-pages, split-pdf (signed out) , crop-pages
- All file formats for split-pdf (signed in)
- Min page requirement of 2 page and max 1500 for split-pdf.
Resolves: [MWPW-165545](https://jira.corp.adobe.com/browse/MWPW-165545)
**Test URLs:**
- https://stage--dc--adobecom.hlx.page/acrobat/online/test/pdf-editor?unitylibs=acrobat1a
- https://stage--dc--adobecom.hlx.page/acrobat/online/test/add-pdf-page-numbers?unitylibs=acrobat1a
- https://stage--dc--adobecom.hlx.page/acrobat/online/test/split-pdf?unitylibs=acrobat1a
- https://stage--dc--adobecom.hlx.page/acrobat/online/test/crop-pdf?unitylibs=acrobat1a
- URL for PSI git check - …
=> MWPW-165545 | Acrobat Batch 1a verbs

unitylibs/core/steps/upload-step.js, unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-ai/service-handler.js, unitylibs/core/workflow/workflow-photoshop/action-binder.js, unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js, unitylibs/scripts/utils.js
In the common utils file, the function getGuestAccessToken is refactored to retrieve the refreshToken when the accessToken has expired.
Note: Added changes for v1 API as well for backward compatibility.
Resolves: [MWPW-163640](https://jira.corp.adobe.com/browse/MWPW-163640)
**Test URLs:**
PS
- Before: https://stage--cc--adobecom.hlx.page/products/photoshop/remove-background?martech=off 
- After: https://stage--cc--adobecom.hlx.page/products/photoshop/remove-background?unitylibs=mwpw-163640&martech=off
- PSI test: https://mwpw-163640--unity--adobecom.hlx.live/drafts/mathuria/remove-background
Express
https://stage--cc--adobecom.hlx.page/drafts/hnv/text2image-test-page?unitylibs=mwpw-163640
PS: This change can be tested on stage only since I am getting CORS error while testing in CC, DC
=> MWPW-163640: Refactor token retrieval in common utils to use refreshToken

unitylibs/core/steps/app-connector.js, unitylibs/core/steps/upload-step.js, unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-ai/service-handler.js, unitylibs/core/workflow/workflow-photoshop/action-binder.js, unitylibs/core/workflow/workflow-photoshop/workflow-photoshop.js, unitylibs/scripts/utils.js
This PR is copy of https://github.com/adobecom/unity/pull/273 along with the bug fix.
Bug fix:
The existing getHeaders() function in utils did not return a key value pair like `headers : {}`. Refactored now to make headers a key value pair at function invocation.
Refactoring:
In the common utils file, the function getGuestAccessToken is refactored to retrieve the refreshToken when the accessToken has expired.
Note: Added changes for v1 API as well for backward compatibility
Resolves: [MWPW-163640](https://jira.corp.adobe.com/browse/MWPW-163640)
**Test URLs:**
PS
- Before: https://stage--cc--adobecom.hlx.page/products/photoshop/remove-background?martech=off 
- After: https://stage--cc--adobecom.hlx.page/products/photoshop/remove-background?unitylibs=mwpw-163640-fix&martech=off
- PSI test: …
=> MWPW-163640: [BugFix] Refactor token retrieval in common utils to use refreshToken

unitylibs/core/workflow/workflow-acrobat/action-binder.js
Fixing the acrobat finalize header failure
**Test URLs:**
=> Fixing the acrobat finalize header failure

unitylibs/core/workflow/workflow-photoshop/action-binder.js
Fix the block on reupload of same image for Chrome and Safari
Resolves: [MWPW-169252](https://jira.corp.adobe.com/browse/MWPW-169252)
**Test URLs:**
- Before: https://main--unity--adobecom.aem.page/drafts/mathuria/remove-backgrond?martech=off
- After: https://MWPW-169252--unity--adobecom.aem.page/remove-backgrond?martech=off
=> MWPW-169252 | Fix the block on reupload of same image for Chrome and Safari

unitylibs/core/styles/styles.css, unitylibs/core/workflow/workflow-photoshop/widget.css, unitylibs/core/workflow/workflow-photoshop/widget.js
- As per figma, updating the button svg to be blue when active
- Making thumbnail load faster by using lower resolution images
Resolves:
[MWPW-169302](https://jira.corp.adobe.com/browse/MWPW-169302)
[MWPW-169285](https://jira.corp.adobe.com/browse/MWPW-169285)
**Test URLs:**
- Before: https://main--unity--adobecom.aem.live/drafts/mathuria/remove-background?martech=off
- After: https://MWPW-169302--unity--adobecom.aem.live/drafts/mathuria/remove-background?martech=off
- Before: https://main--unity--adobecom.aem.live/drafts/mathuria/remove-background-cache?martech=off
- After: https://MWPW-169302--unity--adobecom.aem.live/drafts/mathuria/remove-background-cache?martech=off
=> MWPW-169302 & MWPW-169285 | Making the widget consistent with figma and faster thumbnail loading

unitylibs/core/styles/styles.css
Unity Ps [PROD and Stage] Text is underlined in unity widget in mobile and as per figma there should be no underline.
Fixing this in V2
Resolves: [MWPW-169374](https://jira.corp.adobe.com/browse/MWPW-169374)
**Test URLs:**
- After: https://widgetunderline--unity--adobecom.aem.page/?martech=off
=> MWPW-169374 | Remove underline from button text from mobile in V2

unitylibs/core/workflow/workflow-acrobat/action-binder.js
Cancel button wasn't working after the modularization work and throwing a related console error.
This update fixes the cancel button seen on the transition screen. Clicking cancel will now stop the uploading process. 
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?martech=off
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=transition-cancel&martech=off
Testing notes:
- Add a PDF to upload
- While the file is uploading click the cancel button.
- The uploading process should cancel and take you back to the initial upload screen.
=> Transition screen cancel

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js
Refactor and fix potential issues in fetchFromService and fetchFromServiceWithRetry methods
There seems to be some issue with our fetchFromService and fetchFromServiceWithRetry functions. The 
- Ensured we capture additional logging of 504 timeouts if maxRetryDelay is exceeded and 200 response still hasn't been returned.
- Error has been captured to identify if the response parsing has failed
- Moved "quotaexceeded" and "notentitled" check outside the common fetch API
- fetchFromServiceWithRetry function has been be simplified to use the common fetchFromService method
Testing Notes:
- Sanitise network calls
- In extremely slow network, pdf upload should work fine. 
Resolves: [MWPW-169793](https://jira.corp.adobe.com/browse/MWPW-169793)
**Test URLs:**
- Before: …
=> [MWPW-169793] Finalize API Exceptions

unitylibs/core/workflow/workflow.js
This PR removes the need for the icon expression used for the Unity workflow verb. Now, we’ll get the verb directly from the verb-widget block.
This has a dependency on [this DC PR](https://github.com/adobecom/dc/pull/1071). The DC PR needs to be merged first so this can be tested easily.
Resolves: [MWPW-169785](https://jira.corp.adobe.com/browse/MWPW-169785)
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/drafts/rbogos/acrobat/compress-pdf-new?unitylibs=stage&martech=off
- After: https://stage--dc--adobecom.hlx.page/drafts/rbogos/acrobat/compress-pdf-new?unitylibs=mwpw-169785-performance&martech=off
=> [MWPW-169785] Workflow authoring enhancements to improve performance

unitylibs/core/workflow/workflow-acrobat/action-binder.js
- Avoid settiing Content-Length to '0' if not present as response can be valid and not include this header
- Reverting this line update from https://github.com/adobecom/unity/pull/316
Resolves: [MWPW-170490](https://jira.corp.adobe.com/browse/MWPW-170490)
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/test/pdf-editor?unitylibs=stage&martech=off
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/pdf-editor?unitylibs=MWPW-170490&martech=off
=> MWPW-170490 Avoid setting Content-Length to 0 if not present

unitylibs/core/workflow/workflow-acrobat/action-binder.js
* Fix signed in allowed file type being added to signed out user
Resolves: [MWPW-170525](https://jira.corp.adobe.com/browse/MWPW-170525)
**Test URLs:**
- Before: https://stage--dc--adobecom.aem.page/acrobat/online/split-pdf?unitylibs=stage?martech=off
- After: https://stage--dc--adobecom.aem.page/acrobat/online/split-pdf?unitylibs=filetype?martech=off
=> MWPW-170525-Fix signed in allowed file type being added to signed out user

unitylibs/core/workflow/workflow-acrobat/action-binder.js
- Fixes preloading of splashscreen causing 404.
- Removed duplicate calls to load splash screen
- Action-binder.js clean up
Resolves: Addressing comment made https://github.com/adobecom/unity/pull/314#issuecomment-2759066912
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=batch1b&martech=off
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=preload-fragment&martech=off
**Testing notes:**
- Open up the network tab in dev tools on before and after links.
- Notice splashscreen.plain.html being loaded (preloading)
- Select a file to upload. 
- Notice the 404 for "undefined.plain.html`
- Notice the a 404 for `undefined.plain.html`
- On After link run the same process.
- Notice no 404 and …
=> Splashscreen.plain.html 404

unitylibs/core/workflow/workflow-acrobat/upload-handler.js
Resolves: [MWPW-170550](https://jira.corp.adobe.com/browse/MWPW-170550)
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=arugupta-UploadFix
=> Fixing getUnityLibs undefined error in upload-handler

unitylibs/core/workflow/workflow-acrobat/action-binder.js
* Wait for event dispatched from DC acom code to redirect to acrobat web
* The event is dispatched either on successfully sending the uploaded event to AA or after a timeout of 3 seconds
Resolves: [MWPW-170867](https://jira.corp.adobe.com/browse/MWPW-170867)
**Test URLs:**
- After: https://stage--dc--adobecom.aem.page/acrobat/online/compress-pdf?unitylibs=MWPW-170867
Note: For reference here is the DC code to dispatch the event https://github.com/adobecom/dc/pull/1084/files
This PR is stage PR for below 2 hotfix PRs that will go to main tomorrow
https://github.com/adobecom/unity/pull/334
https://github.com/adobecom/unity/pull/340
**This is needed for validation on stage for hotfix release tomorrow. …
=> [MWPW-170867]-[STAGE] Wait for event dispatched from DC acom code to redirect to acrobat web

unitylibs/core/workflow/workflow-upload/action-binder.js
* Add analytics event when clicked on drop zone to upload file
* Removed dragEvent as it is handled now in Upload code block
* Analytics event added for uploading started
Resolves: [MWPW-171173](https://jira.corp.adobe.com/browse/MWPW-171173)
**Test URLs:**
- Before: https://stage--cc--adobecom.aem.page/creativecloud/animation/testdoc/remove-background?unitylibs=stage&martech=off
- After: https://stage--cc--adobecom.aem.page/creativecloud/animation/testdoc/remove-background?unitylibs=MWPW-171173-analytics&martech=off
Note: this PR is copy of https://github.com/adobecom/unity/pull/341. Because of rebase done on stage reopening it again
=> MWPW-171173- Add analytics events

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js
Testing Notes:
1. Verify there is no break in redirect, success event should go on Redirect 
2. All evets fired are succesfully logged to splunk service
3. Event payloads include the fielsd as per the [wiki](https://wiki.corp.adobe.com/display/~arugupta/Proposal+for+Granular+Error+Tracking+in+Project+Unity+Upload+Workflows) 
**Test URLs:**
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=arugupta-dataPayloadForSplunk
=> Improving payload + adding file metadata in cancel + dispatching success event on redirect

unitylibs/scripts/transition-screen.js
* Code to handle different text for desktop in transition screen
Resolves: [MWPW-171722](https://jira.corp.adobe.com/browse/MWPW-171722)
**Test URLs:**
Test pages to make sure nothing breaks on live experience
- Before: https://stage--cc--adobecom.hlx.page/products/photoshop/online?martech=off&unitylibs=stage
- After: https://stage--cc--adobecom.hlx.page/products/photoshop/online?martech=off&unitylibs=MWPW-171722
Test page to make sure if 2 different text is authored on transition screen fragment before CC phase code goes live doesn't break anything on live experience:
- Before: https://stage--cc--adobecom.hlx.page/products/photoshop/online?martech=off&unitylibs=stage
- After: https://stage--cc--adobecom.hlx.page/products/photoshop/online?martech=off&unitylibs=splash-test
splash-test …
=> [MWPW-171722]Code to handle different text for desktop in transition screen

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js
* Retry for Unity Service API failure for 5XX code
* Retry chunk upload errors with exponential backoff
* Fix "Exception thrown when verifying content: Cannot set property message of which has only a getter"
Resolves: [MWPW-171794](https://jira.corp.adobe.com/browse/MWPW-171794)
Also fixes:
- https://jira.corp.adobe.com/browse/MWPW-171795
- https://jira.corp.adobe.com/browse/MWPW-171796
- https://jira.corp.adobe.com/browse/MWPW-171801
**Test URLs:**
=> [MWPW-171794] Added retry for API calls

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js
* Add analytics for chunk upload success to capture the chunk upload attempt. 
* Capture cancel step as uploading and preuploading
Corresponding Slytherin PR: https://github.com/adobecom/dc/pull/1140 
Resolves: [MWPW-172209](https://jira.corp.adobe.com/browse/MWPW-172209)
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/test/pdf-to-word
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/test/pdf-to-word?unitylibs=chunk-upload-retry-analytics
=> [MWPW-172209] Send analytics to capture retry success for chunk upload

unitylibs/core/workflow/workflow-acrobat/action-binder.js
(cherry picked from commit 486b4b50a0078d90b2e808fdac1ce3c918851e17)
We already have retry for 5xx errors, now added the retry for 429 as well
Resolves: [MWPW-172583](https://jira.corp.adobe.com/browse/MWPW-172583)
**Test URLs:**
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/word-to-pdf?unitylibs=stage
After: https://stage--dc--adobecom.hlx.page/acrobat/online/word-to-pdf?unitylibs=rosahu-MWPW-172583
=> [MWPW-172583] Add retry for 429 error

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/scripts/utils.js
* Stage-specific request to retain all A.com query params post-upload and redirect to acrobat product
Resolves: [MWPW-172470](https://jira.corp.adobe.com/browse/MWPW-172470)
Testing Steps:
- Visit the "After" url
- Add additional query params and refresh the page
- Upload PDF(s) and verify that the same query params are passed to the product URL after successful upload
**Test URLs:**
- After: https://stage--dc--adobecom.aem.page/acrobat/online/compress-pdf?unitylibs=MWPW-172470
=> MWPW-172470 [Stage Only] Preserve all A.com query params when redirecting to product

unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/upload-handler.js
Adds `UTS_Uploaded` query param to the redirect url.
* If upload IS successful, `UTS_Uploaded=${this.uploadTimestamp}` is added to the end of the URL with the timestamp originating from the time of file upload.
Example URL with new query param:
`hhttps://stage.acrobat.adobe.com/us/en/compress-pdf?UTS_Uploaded=1746577791179&unitylibs=upload-success-query-param&martech=off&x_api_client_id=unity&x_api_client_location=compress-pdf&user=frictionless_return_user&attempts=2%2B#assets=urn%3Aaaid%3Asc%3AUS%3Ab4b990e9-62d6-364d-b9dc-efcd1a98ebb3|ic-year-end-check-in-guide.pdf|8982279|application%2Fpdf`
Resolves: [MWPW-171687](https://jira.corp.adobe.com/browse/MWPW-171687)
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?martech=off
- After: …
=> Adding upload success query parameter

unitylibs/core/workflow/workflow-acrobat/upload-handler.js
* Chunk upload failures have started to report into AA as they have categorized as generic errors
* We had previously fixed this by segregating these errors under a different error code
* This fix is to re-bucket these chunk upload failures so they are not tracked in AA as they have been mistakenly spiking up error rates 
Resolves: [MWPW-172495](https://jira.corp.adobe.com/browse/MWPW-172495)
**Test URLs:**
- After: https://stage--dc--adobecom.aem.page/acrobat/online/compress-pdf?unitylibs=MWPW-172495
=> MWPW-172495 Removing chunk upload failures from generic error code bucket

unitylibs/core/workflow/workflow-acrobat/action-binder.js
This PR adds the files count check for the acrobat workflow.
[MWPW-173034](https://jira.corp.adobe.com/browse/MWPW-173034)
This can be tested after the [2b config changes](https://github.com/adobecom/unity/pull/382) are merged.
**Test URLs:**
- Before: https://stage--dc--adobecom.aem.page/acrobat/online/test/rotate-pdf?unitylibs=stage
- After: https://stage--dc--adobecom.aem.page/acrobat/online/test/rotate-pdf?unitylibs=mwpw-173034
=> [MWPW-173034] Added files count check for acrobat workflow

unitylibs/core/workflow/workflow-upload/action-binder.js, unitylibs/core/workflow/workflow.js
* Make Photoshop web redirect on desktop configurable through authoring
Resolves: [MWPW-173471](https://jira.corp.adobe.com/browse/MWPW-173471)
**Test URLs:**
Test Page without the token to enable Photoshop web redirect. All devices should redirect to prelude
- Before: https://stage--cc--adobecom.hlx.page/products/photoshop/online?unitylibs=stage
- After: https://stage--cc--adobecom.hlx.page/products/photoshop/online?unitylibs=desktop-optional
Test Page with token added to enable redirect to Photoshop web on desktop only.
- Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/unity/upload-image1?unitylibs=stage
- After: https://main--cc--adobecom.hlx.page/drafts/ruchika/unity/upload-image1?unitylibs=desktop-optional
=> [MWPW-173471] Make Photoshop web redirect on desktop configurable through authoring

unitylibs/core/workflow/workflow-firefly/widget.js
Fixes bug where clicking on the icon in the dropdown menu doesn't update the selected item correctly.
* Updated dropdown menu icons alt text to be decorative.
**Test URLs:**
- Before: https://main--cc--adobecom.aem.live/drafts/rclayton/firefly/text-to-image?unitylibs=firefly-workflow&martech=off
- After: https://main--cc--adobecom.aem.live/drafts/rclayton/firefly/text-to-image?unitylibs=ff-dropdown-item-click&martech=off
=> Fix verb dropdown item click

unitylibs/core/workflow/workflow-acrobat/action-binder.js
This is duplicate of https://github.com/adobecom/unity/pull/423. Had to create new as the previous one was raised on stage changes. 
Resolves: [MWPW-173666](https://jira.corp.adobe.com/browse/MWPW-173666)
Test URLs:
Before: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=stage
After: https://stage--dc--adobecom.hlx.page/acrobat/online/compress-pdf?unitylibs=fix-MWPW-173666
=> MWPW173666 : Incase of input validation failures, no event goes not even choose file event.

unitylibs/core/workflow/workflow-firefly/widget.css, unitylibs/core/workflow/workflow-firefly/widget.js
* Added aria-labels to selectedVerb button.
* Added aria-label to dropdown selected item.
* Escape key can now close the verbDropdown menu when open.
* Adjust styling of toast error for smaller screens cutting off close button.
* Adjust styling for prompt UI on light backgrounds.
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/unity/firefly/unity-firefly?unitylibs=firefly-workflow&martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/ruchika/unity/firefly/unity-firefly?unitylibs=ff-verb-dd-accessibility&martech=off
=> Accessiblity updates

unitylibs/core/workflow/workflow-acrobat/action-binder.js
This was happening since the error code strings have been changed and the error sheet has not been updated yet
created old vs new error codes and use old error code while fetching the error string from error sheet. I have also added the fallback to use the new error code in case we decide to update the error sheet
Resolves: [MWPW-173836](https://jira.corp.adobe.com/browse/MWPW-173836)
**Test URLs:**
- Before: https://main--dc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=release-052225
- After: https://main--dc--adobecom.hlx.page/acrobat/online/sign-pdf?unitylibs=revert-error-msg
=> [MWPW-173836] Getting 'unable to process the request' for all kind of toast errors

unitylibs/core/workflow/workflow-firefly/widget.css
* Mobile suggested prompts are updated to display only one line (max-viewport 599px).
* Prompt suggestions icon size doesn't change.
Resolves: [MWPW-174049](https://jira.corp.adobe.com/browse/MWPW-174049)
**Test URLs:**
- Before: https://main--cc--adobecom.aem.page/drafts/rclayton/firefly/text-to-image?unitylibs=stage&martech=off
- After: https://main--cc--adobecom.aem.page/drafts/rclayton/firefly/text-to-image?unitylibs=ff-prompt-mobile-clamp&martech=off
=> Mobile prompt truncated to one line

unitylibs/core/workflow/workflow-acrobat/upload-handler.js
!isPdf() was being incorrectly sent instead of isPdf. Fixed now
Testing Notes: 
1. Check file upload for verbs that support single file pdf-only --- signed in user
2. Check for verbs that support non pdf - sfu and mfu --- signed in user
Resolves: [MWPW-174131](https://jira.corp.adobe.com/browse/MWPW-174131)
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/merge-pdf?unitylibs=stage
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/merge-pdf?unitylibs=MWPW-174131
=> MWPW-174131 : Unable to upload on stage A.com page if user is already signed in

unitylibs/core/workflow/workflow-acrobat/action-binder.js
Before 2b feedback=uploaderror was added to redrect url at client side if there is page check failure. With 2b error cases, feedback=uploaderror needs to be passed for input validation failures as well in case of mfu. This is handled at backend. 
Applying the check at client side to not add '**feedback=uploaderror**' if already present in the redirect url
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/rotate-pdf?unitylibs=stage
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/rotate-pdf?unitylibs=errorCaseHandling
=> Handling duplicate feedback=uploaderror addition in redirect url

unitylibs/core/workflow/workflow-acrobat/upload-handler.js
Added the logic to hide transition screen if asset api fails. This was just missing for asset api. Was already in place for connector and finalise apis.
Resolves: [MWPW-174798](https://jira.corp.adobe.com/browse/MWPW-174798)
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.page/acrobat/online/rotate-pdf?unitylibs=stage
- After: https://stage--dc--adobecom.hlx.page/acrobat/online/rotate-pdf?unitylibs=MWPW-174798-500
=> Fix for workflow getting stuck at transition screen if asset api fails 

test/core/workflow/workflow-acrobat/action-binder.test.js, unitylibs/core/workflow/workflow-acrobat/action-binder.js, unitylibs/core/workflow/workflow-acrobat/target-config.json
As a safety check If enabledFeatures is empty let's go ahead and throw a generic error in the UI and log a message in the analytics
Resolves: [MWPW-176626](https://jira.corp.adobe.com/browse/MWPW-176626)
**Test URLs:**
Before: https://stage--dc--adobecom.aem.live/acrobat/online/test/ai-summary-generator?unitylibs=stage
After: https://stage--dc--adobecom.aem.live/acrobat/online/test/ai-summary-generator?unitylibs=missingVerb
=> MWPW-176626 : Error handing for missing verb configuration on unity end

unitylibs/core/workflow/workflow-acrobat/action-binder.js
https://jira.corp.adobe.com/browse/MWPW-181217
Remove page limit of 600 pages for pdf-to-png verb
Resolves: [MWPW-181217](https://jira.corp.adobe.com/browse/MWPW-181217)
Test URLs:
Before: https://stage--dc--adobecom.aem.page/acrobat/online/pdf-to-png
After: https://stage--dc--adobecom.aem.page/acrobat/online/pdf-to-jpg?unitylibs=removePdfToPngPageLimit
Testing Notes
Please test for below scenarios:
For pdf-to-png conversion on unity:
for an input pdf with numPages > 600, it should not give any error
=> [MWPW-181217] remove 600 page limit for pdf-to-png

nala/features/pdf-editor/pdf-editor.test.cjs
* The pdf-editor automation test is currently unstable on the Firefox browser. To avoid false negatives in the CI pipeline, the test should be temporarily skipped when executed under Firefox
* Add `test.skip(browserName === 'firefox', 'Skipping on Firefox')`; in the pdf-editor test file.
* Ensure the test continues to run on Chromium and WebKit browsers.
* Add a console log message during skip for easier tracking in CI logs.
Resolves: [MWPW-181401](https://jira.corp.adobe.com/browse/MWPW-181401)
**Test URLs:**
- After: https://pdf-editor-skip-unity--adobecom.aem.page/?martech=off
=> [MWPW-181401][NALA] Temporarily disable pdf-editor test on firefox browser
